//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqDeviceInfoConfig daqDeviceInfoConfig;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqDeviceType daqDeviceType;

    EXPORTED extern const daqIntfID DAQ_DEVICE_INFO_CONFIG_INTF_ID;
    void EXPORTED daqDeviceInfoConfig_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqDeviceInfoConfig_setName(daqDeviceInfoConfig* self, daqStringObject* name);
    daqErrCode EXPORTED daqDeviceInfoConfig_setConnectionString(daqDeviceInfoConfig* self, daqStringObject* connectionString);
    daqErrCode EXPORTED daqDeviceInfoConfig_setDeviceType(daqDeviceInfoConfig* self, daqDeviceType* deviceType);
    daqErrCode EXPORTED daqDeviceInfoConfig_setManufacturer(daqDeviceInfoConfig* self, daqStringObject* manufacturer);
    daqErrCode EXPORTED daqDeviceInfoConfig_setManufacturerUri(daqDeviceInfoConfig* self, daqStringObject* manufacturerUri);
    daqErrCode EXPORTED daqDeviceInfoConfig_setModel(daqDeviceInfoConfig* self, daqStringObject* model);
    daqErrCode EXPORTED daqDeviceInfoConfig_setProductCode(daqDeviceInfoConfig* self, daqStringObject* productCode);
    daqErrCode EXPORTED daqDeviceInfoConfig_setDeviceRevision(daqDeviceInfoConfig* self, daqStringObject* deviceRevision);
    daqErrCode EXPORTED daqDeviceInfoConfig_setHardwareRevision(daqDeviceInfoConfig* self, daqStringObject* hardwareRevision);
    daqErrCode EXPORTED daqDeviceInfoConfig_setSoftwareRevision(daqDeviceInfoConfig* self, daqStringObject* softwareRevision);
    daqErrCode EXPORTED daqDeviceInfoConfig_setDeviceManual(daqDeviceInfoConfig* self, daqStringObject* deviceManual);
    daqErrCode EXPORTED daqDeviceInfoConfig_setDeviceClass(daqDeviceInfoConfig* self, daqStringObject* deviceClass);
    daqErrCode EXPORTED daqDeviceInfoConfig_setSerialNumber(daqDeviceInfoConfig* self, daqStringObject* serialNumber);
    daqErrCode EXPORTED daqDeviceInfoConfig_setProductInstanceUri(daqDeviceInfoConfig* self, daqStringObject* productInstanceUri);
    daqErrCode EXPORTED daqDeviceInfoConfig_setRevisionCounter(daqDeviceInfoConfig* self, daqInt revisionCounter);
    daqErrCode EXPORTED daqDeviceInfoConfig_setAssetId(daqDeviceInfoConfig* self, daqStringObject* id);
    daqErrCode EXPORTED daqDeviceInfoConfig_setMacAddress(daqDeviceInfoConfig* self, daqStringObject* macAddress);
    daqErrCode EXPORTED daqDeviceInfoConfig_setParentMacAddress(daqDeviceInfoConfig* self, daqStringObject* macAddress);
    daqErrCode EXPORTED daqDeviceInfoConfig_setPlatform(daqDeviceInfoConfig* self, daqStringObject* platform);
    daqErrCode EXPORTED daqDeviceInfoConfig_setPosition(daqDeviceInfoConfig* self, daqInt position);
    daqErrCode EXPORTED daqDeviceInfoConfig_setSystemType(daqDeviceInfoConfig* self, daqStringObject* type);
    daqErrCode EXPORTED daqDeviceInfoConfig_setSystemUuid(daqDeviceInfoConfig* self, daqStringObject* uuid);
    daqErrCode EXPORTED daqDeviceInfoConfig_setLocation(daqDeviceInfoConfig* self, daqStringObject* location);
    daqErrCode EXPORTED daqDeviceInfoConfig_setUserName(daqDeviceInfoConfig* self, daqStringObject* userName);
    daqErrCode EXPORTED daqDeviceInfoConfig_createDeviceInfoConfig(daqDeviceInfoConfig** obj, daqStringObject* name, daqStringObject* connectionString);
    daqErrCode EXPORTED daqDeviceInfoConfig_createDeviceInfoConfigWithCustomSdkVersion(daqDeviceInfoConfig** obj, daqStringObject* name, daqStringObject* connectionString, daqStringObject* sdkVersion);

#ifdef __cplusplus
}
#endif
