//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqDeviceInfo daqDeviceInfo;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqDeviceType daqDeviceType;
    typedef struct daqListObject daqListObject;
    typedef struct daqServerCapability daqServerCapability;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqNetworkInterface daqNetworkInterface;

    EXPORTED extern const daqIntfID DAQ_DEVICE_INFO_INTF_ID;
    void EXPORTED daqDeviceInfo_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqDeviceInfo_getName(daqDeviceInfo* self, daqStringObject** name);
    daqErrCode EXPORTED daqDeviceInfo_getConnectionString(daqDeviceInfo* self, daqStringObject** connectionString);
    daqErrCode EXPORTED daqDeviceInfo_getDeviceType(daqDeviceInfo* self, daqDeviceType** deviceType);
    daqErrCode EXPORTED daqDeviceInfo_getManufacturer(daqDeviceInfo* self, daqStringObject** manufacturer);
    daqErrCode EXPORTED daqDeviceInfo_getManufacturerUri(daqDeviceInfo* self, daqStringObject** manufacturerUri);
    daqErrCode EXPORTED daqDeviceInfo_getModel(daqDeviceInfo* self, daqStringObject** model);
    daqErrCode EXPORTED daqDeviceInfo_getProductCode(daqDeviceInfo* self, daqStringObject** productCode);
    daqErrCode EXPORTED daqDeviceInfo_getDeviceRevision(daqDeviceInfo* self, daqStringObject** deviceRevision);
    daqErrCode EXPORTED daqDeviceInfo_getHardwareRevision(daqDeviceInfo* self, daqStringObject** hardwareRevision);
    daqErrCode EXPORTED daqDeviceInfo_getSoftwareRevision(daqDeviceInfo* self, daqStringObject** softwareRevision);
    daqErrCode EXPORTED daqDeviceInfo_getDeviceManual(daqDeviceInfo* self, daqStringObject** deviceManual);
    daqErrCode EXPORTED daqDeviceInfo_getDeviceClass(daqDeviceInfo* self, daqStringObject** deviceClass);
    daqErrCode EXPORTED daqDeviceInfo_getSerialNumber(daqDeviceInfo* self, daqStringObject** serialNumber);
    daqErrCode EXPORTED daqDeviceInfo_getProductInstanceUri(daqDeviceInfo* self, daqStringObject** productInstanceUri);
    daqErrCode EXPORTED daqDeviceInfo_getRevisionCounter(daqDeviceInfo* self, daqInt* revisionCounter);
    daqErrCode EXPORTED daqDeviceInfo_getAssetId(daqDeviceInfo* self, daqStringObject** id);
    daqErrCode EXPORTED daqDeviceInfo_getMacAddress(daqDeviceInfo* self, daqStringObject** macAddress);
    daqErrCode EXPORTED daqDeviceInfo_getParentMacAddress(daqDeviceInfo* self, daqStringObject** macAddress);
    daqErrCode EXPORTED daqDeviceInfo_getPlatform(daqDeviceInfo* self, daqStringObject** platform);
    daqErrCode EXPORTED daqDeviceInfo_getPosition(daqDeviceInfo* self, daqInt* position);
    daqErrCode EXPORTED daqDeviceInfo_getSystemType(daqDeviceInfo* self, daqStringObject** type);
    daqErrCode EXPORTED daqDeviceInfo_getSystemUuid(daqDeviceInfo* self, daqStringObject** uuid);
    daqErrCode EXPORTED daqDeviceInfo_getCustomInfoPropertyNames(daqDeviceInfo* self, daqListObject** customInfoNames);
    daqErrCode EXPORTED daqDeviceInfo_getSdkVersion(daqDeviceInfo* self, daqStringObject** version);
    daqErrCode EXPORTED daqDeviceInfo_getServerCapabilities(daqDeviceInfo* self, daqListObject** serverCapabilities);
    daqErrCode EXPORTED daqDeviceInfo_getLocation(daqDeviceInfo* self, daqStringObject** location);
    daqErrCode EXPORTED daqDeviceInfo_getConfigurationConnectionInfo(daqDeviceInfo* self, daqServerCapability** connectionInfo);
    daqErrCode EXPORTED daqDeviceInfo_hasServerCapability(daqDeviceInfo* self, daqStringObject* protocolId, daqBool* hasCapability);
    daqErrCode EXPORTED daqDeviceInfo_getServerCapability(daqDeviceInfo* self, daqStringObject* protocolId, daqServerCapability** serverCapability);
    daqErrCode EXPORTED daqDeviceInfo_getNetworkInterfaces(daqDeviceInfo* self, daqDictObject** interfaces);
    daqErrCode EXPORTED daqDeviceInfo_getNetworkInterface(daqDeviceInfo* self, daqStringObject* interfaceName, daqNetworkInterface** intf);
    daqErrCode EXPORTED daqDeviceInfo_getUserName(daqDeviceInfo* self, daqStringObject** userName);
    daqErrCode EXPORTED daqDeviceInfo_getConnectedClientsInfo(daqDeviceInfo* self, daqListObject** connectedClientsInfo);

#ifdef __cplusplus
}
#endif
