//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqServerCapability daqServerCapability;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqListObject daqListObject;
    typedef struct daqIntegerObject daqIntegerObject;

    EXPORTED extern const daqIntfID DAQ_SERVER_CAPABILITY_INTF_ID;
    void EXPORTED daqServerCapability_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqServerCapability_getConnectionString(daqServerCapability* self, daqStringObject** connectionString);
    daqErrCode EXPORTED daqServerCapability_getConnectionStrings(daqServerCapability* self, daqListObject** connectionStrings);
    daqErrCode EXPORTED daqServerCapability_getProtocolName(daqServerCapability* self, daqStringObject** protocolName);
    daqErrCode EXPORTED daqServerCapability_getProtocolId(daqServerCapability* self, daqStringObject** protocolId);
    daqErrCode EXPORTED daqServerCapability_getProtocolType(daqServerCapability* self, daqProtocolType* type);
    daqErrCode EXPORTED daqServerCapability_getPrefix(daqServerCapability* self, daqStringObject** prefix);
    daqErrCode EXPORTED daqServerCapability_getConnectionType(daqServerCapability* self, daqStringObject** type);
    daqErrCode EXPORTED daqServerCapability_getCoreEventsEnabled(daqServerCapability* self, daqBool* enabled);
    daqErrCode EXPORTED daqServerCapability_getAddresses(daqServerCapability* self, daqListObject** addresses);
    daqErrCode EXPORTED daqServerCapability_getPort(daqServerCapability* self, daqIntegerObject** port);
    daqErrCode EXPORTED daqServerCapability_getAddressInfo(daqServerCapability* self, daqListObject** addressInfo);
    daqErrCode EXPORTED daqServerCapability_getProtocolVersion(daqServerCapability* self, daqStringObject** version);

#ifdef __cplusplus
}
#endif
