//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/utility/packet_buffer_builder.h>

#include <opendaq/opendaq.h>
#include <opendaq/packet_buffer_builder.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PACKET_BUFFER_BUILDER_INTF_ID = { daq::IPacketBufferBuilder::Id.Data1, daq::IPacketBufferBuilder::Id.Data2, daq::IPacketBufferBuilder::Id.Data3, daq::IPacketBufferBuilder::Id.Data4_UInt64 };

void daqPacketBufferBuilder_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PACKET_BUFFER_BUILDER_INTF_ID;
}

daqErrCode daqPacketBufferBuilder_getContext(daqPacketBufferBuilder* self, daqContext** context)
{
    return reinterpret_cast<daq::IPacketBufferBuilder*>(self)->getContext(reinterpret_cast<daq::IContext**>(context));
}

daqErrCode daqPacketBufferBuilder_setContext(daqPacketBufferBuilder* self, daqContext* context)
{
    return reinterpret_cast<daq::IPacketBufferBuilder*>(self)->setContext(reinterpret_cast<daq::IContext*>(context));
}

daqErrCode daqPacketBufferBuilder_getSizeInBytes(daqPacketBufferBuilder* self, daqCSizeT* sizeInBytes)
{
    return reinterpret_cast<daq::IPacketBufferBuilder*>(self)->getSizeInBytes(sizeInBytes);
}

daqErrCode daqPacketBufferBuilder_setSizeInBytes(daqPacketBufferBuilder* self, daqCSizeT sizeInBytes)
{
    return reinterpret_cast<daq::IPacketBufferBuilder*>(self)->setSizeInBytes(sizeInBytes);
}

daqErrCode daqPacketBufferBuilder_build(daqPacketBufferBuilder* self, daqPacketBuffer** buffer)
{
    return reinterpret_cast<daq::IPacketBufferBuilder*>(self)->build(reinterpret_cast<daq::IPacketBuffer**>(buffer));
}

daqErrCode daqPacketBufferBuilder_createPacketBufferBuilder(daqPacketBufferBuilder** obj)
{
    daq::IPacketBufferBuilder* ptr = nullptr;
    daqErrCode err = daq::createPacketBufferBuilder(&ptr);
    *obj = reinterpret_cast<daqPacketBufferBuilder*>(ptr);
    return err;
}
