//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/utility/packet_buffer.h>

#include <opendaq/opendaq.h>
#include <opendaq/packet_buffer.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PACKET_BUFFER_INTF_ID = { daq::IPacketBuffer::Id.Data1, daq::IPacketBuffer::Id.Data2, daq::IPacketBuffer::Id.Data3, daq::IPacketBuffer::Id.Data4_UInt64 };

void daqPacketBuffer_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PACKET_BUFFER_INTF_ID;
}

daqErrCode daqPacketBuffer_createPacket(daqPacketBuffer* self, daqCSizeT sampleCount, daqDataDescriptor* desc, daqPacket* domainPacket, daqDataPacket** packet)
{
    return reinterpret_cast<daq::IPacketBuffer*>(self)->createPacket(sampleCount, reinterpret_cast<daq::IDataDescriptor*>(desc), reinterpret_cast<daq::IPacket*>(domainPacket), reinterpret_cast<daq::IDataPacket**>(packet));
}

daqErrCode daqPacketBuffer_getMaxAvailableContinousSampleCount(daqPacketBuffer* self, daqDataDescriptor* desc, daqCSizeT* count)
{
    return reinterpret_cast<daq::IPacketBuffer*>(self)->getMaxAvailableContinousSampleCount(reinterpret_cast<daq::IDataDescriptor*>(desc), count);
}

daqErrCode daqPacketBuffer_getAvailableSampleCount(daqPacketBuffer* self, daqDataDescriptor* desc, daqCSizeT* count)
{
    return reinterpret_cast<daq::IPacketBuffer*>(self)->getAvailableSampleCount(reinterpret_cast<daq::IDataDescriptor*>(desc), count);
}

daqErrCode daqPacketBuffer_resize(daqPacketBuffer* self, daqCSizeT sizeInBytes)
{
    return reinterpret_cast<daq::IPacketBuffer*>(self)->resize(sizeInBytes);
}

daqErrCode daqPacketBuffer_createPacketBuffer(daqPacketBuffer** obj, daqPacketBufferBuilder* builder)
{
    daq::IPacketBuffer* ptr = nullptr;
    daqErrCode err = daq::createPacketBuffer(&ptr, reinterpret_cast<daq::IPacketBufferBuilder*>(builder));
    *obj = reinterpret_cast<daqPacketBuffer*>(ptr);
    return err;
}
