//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/signal/wrapped_data_packet.h>

#include <opendaq/opendaq.h>
#include <opendaq/wrapped_data_packet.h>

#include <copendaq_private.h>

const daqIntfID DAQ_WRAPPED_DATA_PACKET_INTF_ID = { daq::IWrappedDataPacket::Id.Data1, daq::IWrappedDataPacket::Id.Data2, daq::IWrappedDataPacket::Id.Data3, daq::IWrappedDataPacket::Id.Data4_UInt64 };

void daqWrappedDataPacket_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_WRAPPED_DATA_PACKET_INTF_ID;
}

daqErrCode daqWrappedDataPacket_getSourcePacket(daqWrappedDataPacket* self, daqDataPacket** sourcePacket)
{
    return reinterpret_cast<daq::IWrappedDataPacket*>(self)->getSourcePacket(reinterpret_cast<daq::IDataPacket**>(sourcePacket));
}

daqErrCode daqDataPacket_createWrappedDataPacket(daqDataPacket** obj, daqDataPacket* sourcePacket, daqDataDescriptor* descriptor)
{
    daq::IDataPacket* ptr = nullptr;
    daqErrCode err = daq::createWrappedDataPacket(&ptr, reinterpret_cast<daq::IDataPacket*>(sourcePacket), reinterpret_cast<daq::IDataDescriptor*>(descriptor));
    *obj = reinterpret_cast<daqDataPacket*>(ptr);
    return err;
}
