//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqDataPacket daqDataPacket;
    typedef struct daqDataDescriptor daqDataDescriptor;
    typedef struct daqNumber daqNumber;
    typedef struct daqTypeManager daqTypeManager;
    typedef struct daqDeleter daqDeleter;

    EXPORTED extern const daqIntfID DAQ_DATA_PACKET_INTF_ID;
    void EXPORTED daqDataPacket_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqDataPacket_getDataDescriptor(daqDataPacket* self, daqDataDescriptor** descriptor);
    daqErrCode EXPORTED daqDataPacket_getSampleCount(daqDataPacket* self, daqCSizeT* sampleCount);
    daqErrCode EXPORTED daqDataPacket_getOffset(daqDataPacket* self, daqNumber** offset);
    daqErrCode EXPORTED daqDataPacket_getData(daqDataPacket* self, void** address);
    daqErrCode EXPORTED daqDataPacket_getRawData(daqDataPacket* self, void** address);
    daqErrCode EXPORTED daqDataPacket_getDataSize(daqDataPacket* self, daqCSizeT* dataSize);
    daqErrCode EXPORTED daqDataPacket_getRawDataSize(daqDataPacket* self, daqCSizeT* rawDataSize);
    daqErrCode EXPORTED daqDataPacket_getDomainPacket(daqDataPacket* self, daqDataPacket** packet);
    daqErrCode EXPORTED daqDataPacket_getPacketId(daqDataPacket* self, daqCInt* packetId);
    daqErrCode EXPORTED daqDataPacket_getLastValue(daqDataPacket* self, daqBaseObject** value, daqTypeManager* typeManager);
    daqErrCode EXPORTED daqDataPacket_getValueByIndex(daqDataPacket* self, daqBaseObject** value, daqCSizeT index, daqTypeManager* typeManager);
    daqErrCode EXPORTED daqDataPacket_getRawLastValue(daqDataPacket* self, void** value);
    daqErrCode EXPORTED daqDataPacket_getRawValueByIndex(daqDataPacket* self, void** value, daqCSizeT index);
    daqErrCode EXPORTED daqDataPacket_createDataPacket(daqDataPacket** obj, daqDataDescriptor* descriptor, daqCSizeT sampleCount, daqNumber* offset);
    daqErrCode EXPORTED daqDataPacket_createDataPacketWithExternalMemory(daqDataPacket** obj, daqDataPacket* domainPacket, daqDataDescriptor* descriptor, daqCSizeT sampleCount, daqNumber* offset, void* externalMemory, daqDeleter* deleter, daqCSizeT bufferSize);
    daqErrCode EXPORTED daqDataPacket_createDataPacketWithDomain(daqDataPacket** obj, daqDataPacket* domainPacket, daqDataDescriptor* descriptor, daqCSizeT sampleCount, daqNumber* offset);
    daqErrCode EXPORTED daqDataPacket_createConstantDataPacketWithDomain(daqDataPacket** obj, daqDataPacket* domainPacket, daqDataDescriptor* descriptor, daqCSizeT sampleCount, void* initialValue, void* otherValues, daqCSizeT otherValueCount);

#ifdef __cplusplus
}
#endif
