//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqEventPacket daqEventPacket;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqDataDescriptor daqDataDescriptor;
    typedef struct daqNumber daqNumber;

    EXPORTED extern const daqIntfID DAQ_EVENT_PACKET_INTF_ID;
    void EXPORTED daqEventPacket_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqEventPacket_getEventId(daqEventPacket* self, daqStringObject** id);
    daqErrCode EXPORTED daqEventPacket_getParameters(daqEventPacket* self, daqDictObject** parameters);
    daqErrCode EXPORTED daqEventPacket_createEventPacket(daqEventPacket** obj, daqStringObject* id, daqDictObject* params);
    daqErrCode EXPORTED daqEventPacket_createDataDescriptorChangedEventPacket(daqEventPacket** obj, daqDataDescriptor* dataDescriptor, daqDataDescriptor* domainDataDescriptor);
    daqErrCode EXPORTED daqEventPacket_createImplicitDomainGapDetectedEventPacket(daqEventPacket** obj, daqNumber* diff);

#ifdef __cplusplus
}
#endif
