//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqComponentUpdateContext daqComponentUpdateContext;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqComponent daqComponent;
    typedef struct daqSignal daqSignal;
    typedef struct daqDeviceUpdateOptions daqDeviceUpdateOptions;
    typedef struct daqUpdateParameters daqUpdateParameters;

    EXPORTED extern const daqIntfID DAQ_COMPONENT_UPDATE_CONTEXT_INTF_ID;
    void EXPORTED daqComponentUpdateContext_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqComponentUpdateContext_setInputPortConnection(daqComponentUpdateContext* self, daqStringObject* parentId, daqStringObject* portId, daqStringObject* signalId);
    daqErrCode EXPORTED daqComponentUpdateContext_getInputPortConnections(daqComponentUpdateContext* self, daqStringObject* parentId, daqDictObject** connections);
    daqErrCode EXPORTED daqComponentUpdateContext_removeInputPortConnection(daqComponentUpdateContext* self, daqStringObject* parentId);
    daqErrCode EXPORTED daqComponentUpdateContext_setRootComponent(daqComponentUpdateContext* self, daqComponent* baseComponent);
    daqErrCode EXPORTED daqComponentUpdateContext_getRootComponent(daqComponentUpdateContext* self, daqComponent** rootComponent);
    daqErrCode EXPORTED daqComponentUpdateContext_getSignal(daqComponentUpdateContext* self, daqStringObject* parentId, daqStringObject* portId, daqSignal** signal);
    daqErrCode EXPORTED daqComponentUpdateContext_setSignalDependency(daqComponentUpdateContext* self, daqStringObject* signalId, daqStringObject* parentId);
    daqErrCode EXPORTED daqComponentUpdateContext_addDeviceRemapping(daqComponentUpdateContext* self, daqStringObject* originalDeviceId, daqStringObject* newDeviceId);
    daqErrCode EXPORTED daqComponentUpdateContext_getDeviceUpdateOptionsWithLocalIdOrNull(daqComponentUpdateContext* self, daqStringObject* localId, daqDeviceUpdateOptions** options);
    daqErrCode EXPORTED daqComponentUpdateContext_remapInputPortConnections(daqComponentUpdateContext* self);
    daqErrCode EXPORTED daqComponentUpdateContext_getUpdateParameters(daqComponentUpdateContext* self, daqUpdateParameters** updateParameters);
    daqErrCode EXPORTED daqComponentUpdateContext_overrideState(daqComponentUpdateContext* self, daqComponentUpdateContext* updateContext);
    daqErrCode EXPORTED daqComponentUpdateContext_getInternalState(daqComponentUpdateContext* self, daqDictObject** state);

#ifdef __cplusplus
}
#endif
