//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/opendaq/module_authenticator.h>

#include <opendaq/opendaq.h>
#include <opendaq/module_authenticator.h>

#include <copendaq_private.h>

const daqIntfID DAQ_MODULE_AUTHENTICATOR_INTF_ID = { daq::IModuleAuthenticator::Id.Data1, daq::IModuleAuthenticator::Id.Data2, daq::IModuleAuthenticator::Id.Data3, daq::IModuleAuthenticator::Id.Data4_UInt64 };

void daqModuleAuthenticator_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_MODULE_AUTHENTICATOR_INTF_ID;
}

daqErrCode daqModuleAuthenticator_authenticateModuleBinary(daqModuleAuthenticator* self, daqBool* binaryValid, daqString** vendorKey, daqString* binaryPath)
{
    return reinterpret_cast<daq::IModuleAuthenticator*>(self)->authenticateModuleBinary(binaryValid, reinterpret_cast<daq::IString**>(vendorKey), reinterpret_cast<daq::IString*>(binaryPath));
}

daqErrCode daqModuleAuthenticator_setLogger(daqModuleAuthenticator* self, daqLogger* logger)
{
    return reinterpret_cast<daq::IModuleAuthenticator*>(self)->setLogger(reinterpret_cast<daq::ILogger*>(logger));
}
