//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/component/component_update_context.h>

#include <opendaq/opendaq.h>
#include <opendaq/component_update_context.h>

#include <copendaq_private.h>

const daqIntfID DAQ_COMPONENT_UPDATE_CONTEXT_INTF_ID = { daq::IComponentUpdateContext::Id.Data1, daq::IComponentUpdateContext::Id.Data2, daq::IComponentUpdateContext::Id.Data3, daq::IComponentUpdateContext::Id.Data4_UInt64 };

void daqComponentUpdateContext_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_COMPONENT_UPDATE_CONTEXT_INTF_ID;
}

daqErrCode daqComponentUpdateContext_setInputPortConnection(daqComponentUpdateContext* self, daqStringObject* parentId, daqStringObject* portId, daqStringObject* signalId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->setInputPortConnection(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IString*>(portId), reinterpret_cast<daq::IString*>(signalId));
}

daqErrCode daqComponentUpdateContext_getInputPortConnections(daqComponentUpdateContext* self, daqStringObject* parentId, daqDictObject** connections)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getInputPortConnections(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IDict**>(connections));
}

daqErrCode daqComponentUpdateContext_removeInputPortConnection(daqComponentUpdateContext* self, daqStringObject* parentId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->removeInputPortConnection(reinterpret_cast<daq::IString*>(parentId));
}

daqErrCode daqComponentUpdateContext_setRootComponent(daqComponentUpdateContext* self, daqComponent* baseComponent)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->setRootComponent(reinterpret_cast<daq::IComponent*>(baseComponent));
}

daqErrCode daqComponentUpdateContext_getRootComponent(daqComponentUpdateContext* self, daqComponent** rootComponent)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getRootComponent(reinterpret_cast<daq::IComponent**>(rootComponent));
}

daqErrCode daqComponentUpdateContext_getSignal(daqComponentUpdateContext* self, daqStringObject* parentId, daqStringObject* portId, daqSignal** signal)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getSignal(reinterpret_cast<daq::IString*>(parentId), reinterpret_cast<daq::IString*>(portId), reinterpret_cast<daq::ISignal**>(signal));
}

daqErrCode daqComponentUpdateContext_setSignalDependency(daqComponentUpdateContext* self, daqStringObject* signalId, daqStringObject* parentId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->setSignalDependency(reinterpret_cast<daq::IString*>(signalId), reinterpret_cast<daq::IString*>(parentId));
}

daqErrCode daqComponentUpdateContext_addDeviceRemapping(daqComponentUpdateContext* self, daqStringObject* originalDeviceId, daqStringObject* newDeviceId)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->addDeviceRemapping(reinterpret_cast<daq::IString*>(originalDeviceId), reinterpret_cast<daq::IString*>(newDeviceId));
}

daqErrCode daqComponentUpdateContext_getDeviceUpdateOptionsWithLocalIdOrNull(daqComponentUpdateContext* self, daqStringObject* localId, daqDeviceUpdateOptions** options)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getDeviceUpdateOptionsWithLocalIdOrNull(reinterpret_cast<daq::IString*>(localId), reinterpret_cast<daq::IDeviceUpdateOptions**>(options));
}

daqErrCode daqComponentUpdateContext_remapInputPortConnections(daqComponentUpdateContext* self)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->remapInputPortConnections();
}

daqErrCode daqComponentUpdateContext_getUpdateParameters(daqComponentUpdateContext* self, daqUpdateParameters** updateParameters)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getUpdateParameters(reinterpret_cast<daq::IUpdateParameters**>(updateParameters));
}

daqErrCode daqComponentUpdateContext_overrideState(daqComponentUpdateContext* self, daqComponentUpdateContext* updateContext)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->overrideState(reinterpret_cast<daq::IComponentUpdateContext*>(updateContext));
}

daqErrCode daqComponentUpdateContext_getInternalState(daqComponentUpdateContext* self, daqDictObject** state)
{
    return reinterpret_cast<daq::IComponentUpdateContext*>(self)->getInternalState(reinterpret_cast<daq::IDict**>(state));
}
