//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/device/connected_client_info.h>

#include <opendaq/opendaq.h>
#include <opendaq/connected_client_info.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CONNECTED_CLIENT_INFO_INTF_ID = { daq::IConnectedClientInfo::Id.Data1, daq::IConnectedClientInfo::Id.Data2, daq::IConnectedClientInfo::Id.Data3, daq::IConnectedClientInfo::Id.Data4_UInt64 };

void daqConnectedClientInfo_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CONNECTED_CLIENT_INFO_INTF_ID;
}

daqErrCode daqConnectedClientInfo_getAddress(daqConnectedClientInfo* self, daqStringObject** address)
{
    return reinterpret_cast<daq::IConnectedClientInfo*>(self)->getAddress(reinterpret_cast<daq::IString**>(address));
}

daqErrCode daqConnectedClientInfo_getProtocolType(daqConnectedClientInfo* self, daqProtocolType* type)
{
    return reinterpret_cast<daq::IConnectedClientInfo*>(self)->getProtocolType(reinterpret_cast<daq::ProtocolType*>(type));
}

daqErrCode daqConnectedClientInfo_getProtocolName(daqConnectedClientInfo* self, daqStringObject** protocolName)
{
    return reinterpret_cast<daq::IConnectedClientInfo*>(self)->getProtocolName(reinterpret_cast<daq::IString**>(protocolName));
}

daqErrCode daqConnectedClientInfo_getClientTypeName(daqConnectedClientInfo* self, daqStringObject** type)
{
    return reinterpret_cast<daq::IConnectedClientInfo*>(self)->getClientTypeName(reinterpret_cast<daq::IString**>(type));
}

daqErrCode daqConnectedClientInfo_getHostName(daqConnectedClientInfo* self, daqStringObject** hostName)
{
    return reinterpret_cast<daq::IConnectedClientInfo*>(self)->getHostName(reinterpret_cast<daq::IString**>(hostName));
}

daqErrCode daqConnectedClientInfo_createConnectedClientInfo(daqConnectedClientInfo** obj)
{
    daq::IConnectedClientInfo* ptr = nullptr;
    daqErrCode err = daq::createConnectedClientInfo(&ptr);
    *obj = reinterpret_cast<daqConnectedClientInfo*>(ptr);
    return err;
}

daqErrCode daqConnectedClientInfo_createConnectedClientInfoWithParams(daqConnectedClientInfo** obj, daqStringObject* address, daqProtocolType protocolType, daqStringObject* protocolName, daqStringObject* clientType, daqStringObject* hostName)
{
    daq::IConnectedClientInfo* ptr = nullptr;
    daqErrCode err = daq::createConnectedClientInfoWithParams(&ptr, reinterpret_cast<daq::IString*>(address), static_cast<daq::ProtocolType>(protocolType), reinterpret_cast<daq::IString*>(protocolName), reinterpret_cast<daq::IString*>(clientType), reinterpret_cast<daq::IString*>(hostName));
    *obj = reinterpret_cast<daqConnectedClientInfo*>(ptr);
    return err;
}
