//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/device/connection_status_container_private.h>

#include <opendaq/opendaq.h>
#include <opendaq/connection_status_container_private.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CONNECTION_STATUS_CONTAINER_PRIVATE_INTF_ID = { daq::IConnectionStatusContainerPrivate::Id.Data1, daq::IConnectionStatusContainerPrivate::Id.Data2, daq::IConnectionStatusContainerPrivate::Id.Data3, daq::IConnectionStatusContainerPrivate::Id.Data4_UInt64 };

void daqConnectionStatusContainerPrivate_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CONNECTION_STATUS_CONTAINER_PRIVATE_INTF_ID;
}

daqErrCode daqConnectionStatusContainerPrivate_addConfigurationConnectionStatus(daqConnectionStatusContainerPrivate* self, daqStringObject* connectionString, daqEnumerationObject* initialValue)
{
    return reinterpret_cast<daq::IConnectionStatusContainerPrivate*>(self)->addConfigurationConnectionStatus(reinterpret_cast<daq::IString*>(connectionString), reinterpret_cast<daq::IEnumeration*>(initialValue));
}

daqErrCode daqConnectionStatusContainerPrivate_addStreamingConnectionStatus(daqConnectionStatusContainerPrivate* self, daqStringObject* connectionString, daqEnumerationObject* initialValue, daqStreaming* streamingObject)
{
    return reinterpret_cast<daq::IConnectionStatusContainerPrivate*>(self)->addStreamingConnectionStatus(reinterpret_cast<daq::IString*>(connectionString), reinterpret_cast<daq::IEnumeration*>(initialValue), reinterpret_cast<daq::IStreaming*>(streamingObject));
}

daqErrCode daqConnectionStatusContainerPrivate_removeStreamingConnectionStatus(daqConnectionStatusContainerPrivate* self, daqStringObject* connectionString)
{
    return reinterpret_cast<daq::IConnectionStatusContainerPrivate*>(self)->removeStreamingConnectionStatus(reinterpret_cast<daq::IString*>(connectionString));
}

daqErrCode daqConnectionStatusContainerPrivate_updateConnectionStatus(daqConnectionStatusContainerPrivate* self, daqStringObject* connectionString, daqEnumerationObject* value, daqStreaming* streamingObject)
{
    return reinterpret_cast<daq::IConnectionStatusContainerPrivate*>(self)->updateConnectionStatus(reinterpret_cast<daq::IString*>(connectionString), reinterpret_cast<daq::IEnumeration*>(value), reinterpret_cast<daq::IStreaming*>(streamingObject));
}

daqErrCode daqConnectionStatusContainerPrivate_updateConnectionStatusWithMessage(daqConnectionStatusContainerPrivate* self, daqStringObject* connectionString, daqEnumerationObject* value, daqStreaming* streamingObject, daqStringObject* message)
{
    return reinterpret_cast<daq::IConnectionStatusContainerPrivate*>(self)->updateConnectionStatusWithMessage(reinterpret_cast<daq::IString*>(connectionString), reinterpret_cast<daq::IEnumeration*>(value), reinterpret_cast<daq::IStreaming*>(streamingObject), reinterpret_cast<daq::IString*>(message));
}
