//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/core_event_args.h>

#include <opendaq/opendaq.h>
#include <coreobjects/core_event_args.h>

#include <copendaq_private.h>

const daqIntfID DAQ_CORE_EVENT_ARGS_INTF_ID = { daq::ICoreEventArgs::Id.Data1, daq::ICoreEventArgs::Id.Data2, daq::ICoreEventArgs::Id.Data3, daq::ICoreEventArgs::Id.Data4_UInt64 };

void daqCoreEventArgs_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_CORE_EVENT_ARGS_INTF_ID;
}

daqErrCode daqCoreEventArgs_getParameters(daqCoreEventArgs* self, daqDictObject** parameters)
{
    return reinterpret_cast<daq::ICoreEventArgs*>(self)->getParameters(reinterpret_cast<daq::IDict**>(parameters));
}

daqErrCode daqCoreEventArgs_createCoreEventArgs(daqCoreEventArgs** obj, daqCoreEventId eventId, daqStringObject* eventName, daqDictObject* parameters)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgs(&ptr, static_cast<daq::CoreEventId>(eventId), reinterpret_cast<daq::IString*>(eventName), reinterpret_cast<daq::IDict*>(parameters));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsPropertyValueChanged(daqCoreEventArgs** obj, daqPropertyObject* propOwner, daqStringObject* propName, daqBaseObject* value, daqStringObject* path)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsPropertyValueChanged(&ptr, reinterpret_cast<daq::IPropertyObject*>(propOwner), reinterpret_cast<daq::IString*>(propName), reinterpret_cast<daq::IBaseObject*>(value), reinterpret_cast<daq::IString*>(path));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsPropertyObjectUpdateEnd(daqCoreEventArgs** obj, daqPropertyObject* propOwner, daqDictObject* updatedProperties, daqStringObject* path)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsPropertyObjectUpdateEnd(&ptr, reinterpret_cast<daq::IPropertyObject*>(propOwner), reinterpret_cast<daq::IDict*>(updatedProperties), reinterpret_cast<daq::IString*>(path));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsPropertyAdded(daqCoreEventArgs** obj, daqPropertyObject* propOwner, daqProperty* prop, daqStringObject* path)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsPropertyAdded(&ptr, reinterpret_cast<daq::IPropertyObject*>(propOwner), reinterpret_cast<daq::IProperty*>(prop), reinterpret_cast<daq::IString*>(path));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsPropertyRemoved(daqCoreEventArgs** obj, daqPropertyObject* propOwner, daqStringObject* propName, daqStringObject* path)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsPropertyRemoved(&ptr, reinterpret_cast<daq::IPropertyObject*>(propOwner), reinterpret_cast<daq::IString*>(propName), reinterpret_cast<daq::IString*>(path));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsTypeAdded(daqCoreEventArgs** obj, daqType* type)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsTypeAdded(&ptr, reinterpret_cast<daq::IType*>(type));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsTypeRemoved(daqCoreEventArgs** obj, daqStringObject* typeName)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsTypeRemoved(&ptr, reinterpret_cast<daq::IString*>(typeName));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}

daqErrCode daqCoreEventArgs_createCoreEventArgsPropertyOrderChanged(daqCoreEventArgs** obj, daqPropertyObject* propOwner, daqListObject* propertyOrder, daqStringObject* path)
{
    daq::ICoreEventArgs* ptr = nullptr;
    daqErrCode err = daq::createCoreEventArgsPropertyOrderChanged(&ptr, reinterpret_cast<daq::IPropertyObject*>(propOwner), reinterpret_cast<daq::IList*>(propertyOrder), reinterpret_cast<daq::IString*>(path));
    *obj = reinterpret_cast<daqCoreEventArgs*>(ptr);
    return err;
}
