//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/mutex.h>

#include <opendaq/opendaq.h>
#include <coreobjects/mutex.h>

#include <copendaq_private.h>

const daqIntfID DAQ_MUTEX_INTF_ID = { daq::IMutex::Id.Data1, daq::IMutex::Id.Data2, daq::IMutex::Id.Data3, daq::IMutex::Id.Data4_UInt64 };

void daqMutex_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_MUTEX_INTF_ID;
}

daqErrCode daqMutex_lock(daqMutex* self)
{
    return reinterpret_cast<daq::IMutex*>(self)->lock();
}

daqErrCode daqMutex_tryLock(daqMutex* self, daqCBool* succeeded)
{
    return reinterpret_cast<daq::IMutex*>(self)->tryLock(succeeded);
}

daqErrCode daqMutex_unlock(daqMutex* self)
{
    return reinterpret_cast<daq::IMutex*>(self)->unlock();
}

daqErrCode daqMutex_createMutex(daqMutex** obj)
{
    daq::IMutex* ptr = nullptr;
    daqErrCode err = daq::createMutex(&ptr);
    *obj = reinterpret_cast<daqMutex*>(ptr);
    return err;
}
