//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/property.h>

#include <opendaq/opendaq.h>
#include <coreobjects/property.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROPERTY_INTF_ID = { daq::IProperty::Id.Data1, daq::IProperty::Id.Data2, daq::IProperty::Id.Data3, daq::IProperty::Id.Data4_UInt64 };

void daqProperty_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PROPERTY_INTF_ID;
}

daqErrCode daqProperty_getValueType(daqProperty* self, daqCoreType* type)
{
    return reinterpret_cast<daq::IProperty*>(self)->getValueType(reinterpret_cast<daq::CoreType*>(type));
}

daqErrCode daqProperty_getKeyType(daqProperty* self, daqCoreType* type)
{
    return reinterpret_cast<daq::IProperty*>(self)->getKeyType(reinterpret_cast<daq::CoreType*>(type));
}

daqErrCode daqProperty_getItemType(daqProperty* self, daqCoreType* type)
{
    return reinterpret_cast<daq::IProperty*>(self)->getItemType(reinterpret_cast<daq::CoreType*>(type));
}

daqErrCode daqProperty_getName(daqProperty* self, daqStringObject** name)
{
    return reinterpret_cast<daq::IProperty*>(self)->getName(reinterpret_cast<daq::IString**>(name));
}

daqErrCode daqProperty_getDescription(daqProperty* self, daqStringObject** description)
{
    return reinterpret_cast<daq::IProperty*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqProperty_getUnit(daqProperty* self, daqUnit** unit)
{
    return reinterpret_cast<daq::IProperty*>(self)->getUnit(reinterpret_cast<daq::IUnit**>(unit));
}

daqErrCode daqProperty_getMinValue(daqProperty* self, daqNumber** min)
{
    return reinterpret_cast<daq::IProperty*>(self)->getMinValue(reinterpret_cast<daq::INumber**>(min));
}

daqErrCode daqProperty_getMaxValue(daqProperty* self, daqNumber** max)
{
    return reinterpret_cast<daq::IProperty*>(self)->getMaxValue(reinterpret_cast<daq::INumber**>(max));
}

daqErrCode daqProperty_getDefaultValue(daqProperty* self, daqBaseObject** value)
{
    return reinterpret_cast<daq::IProperty*>(self)->getDefaultValue(reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqProperty_getSuggestedValues(daqProperty* self, daqListObject** values)
{
    return reinterpret_cast<daq::IProperty*>(self)->getSuggestedValues(reinterpret_cast<daq::IList**>(values));
}

daqErrCode daqProperty_getVisible(daqProperty* self, daqBool* visible)
{
    return reinterpret_cast<daq::IProperty*>(self)->getVisible(visible);
}

daqErrCode daqProperty_getReadOnly(daqProperty* self, daqBool* readOnly)
{
    return reinterpret_cast<daq::IProperty*>(self)->getReadOnly(readOnly);
}

daqErrCode daqProperty_getSelectionValues(daqProperty* self, daqBaseObject** values)
{
    return reinterpret_cast<daq::IProperty*>(self)->getSelectionValues(reinterpret_cast<daq::IBaseObject**>(values));
}

daqErrCode daqProperty_getReferencedProperty(daqProperty* self, daqProperty** property)
{
    return reinterpret_cast<daq::IProperty*>(self)->getReferencedProperty(reinterpret_cast<daq::IProperty**>(property));
}

daqErrCode daqProperty_getIsReferenced(daqProperty* self, daqBool* isReferenced)
{
    return reinterpret_cast<daq::IProperty*>(self)->getIsReferenced(isReferenced);
}

daqErrCode daqProperty_getValidator(daqProperty* self, daqValidator** validator)
{
    return reinterpret_cast<daq::IProperty*>(self)->getValidator(reinterpret_cast<daq::IValidator**>(validator));
}

daqErrCode daqProperty_getCoercer(daqProperty* self, daqCoercer** coercer)
{
    return reinterpret_cast<daq::IProperty*>(self)->getCoercer(reinterpret_cast<daq::ICoercer**>(coercer));
}

daqErrCode daqProperty_getCallableInfo(daqProperty* self, daqCallableInfo** callable)
{
    return reinterpret_cast<daq::IProperty*>(self)->getCallableInfo(reinterpret_cast<daq::ICallableInfo**>(callable));
}

daqErrCode daqProperty_getStructType(daqProperty* self, daqStructType** structType)
{
    return reinterpret_cast<daq::IProperty*>(self)->getStructType(reinterpret_cast<daq::IStructType**>(structType));
}

daqErrCode daqProperty_getOnPropertyValueWrite(daqProperty* self, daqEvent** event)
{
    return reinterpret_cast<daq::IProperty*>(self)->getOnPropertyValueWrite(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqProperty_getOnPropertyValueRead(daqProperty* self, daqEvent** event)
{
    return reinterpret_cast<daq::IProperty*>(self)->getOnPropertyValueRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqProperty_getValue(daqProperty* self, daqBaseObject** value)
{
    return reinterpret_cast<daq::IProperty*>(self)->getValue(reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqProperty_setValue(daqProperty* self, daqBaseObject* value)
{
    return reinterpret_cast<daq::IProperty*>(self)->setValue(reinterpret_cast<daq::IBaseObject*>(value));
}

daqErrCode daqProperty_getOnSuggestedValuesRead(daqProperty* self, daqEvent** event)
{
    return reinterpret_cast<daq::IProperty*>(self)->getOnSuggestedValuesRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqProperty_getOnSelectionValuesRead(daqProperty* self, daqEvent** event)
{
    return reinterpret_cast<daq::IProperty*>(self)->getOnSelectionValuesRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqProperty_getPropertyType(daqProperty* self, daqPropertyType* type)
{
    return reinterpret_cast<daq::IProperty*>(self)->getPropertyType(reinterpret_cast<daq::PropertyType*>(type));
}

daqErrCode daqProperty_createBoolProperty(daqProperty** obj, daqStringObject* name, daqBooleanObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createBoolProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IBoolean*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createIntProperty(daqProperty** obj, daqStringObject* name, daqIntegerObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createIntProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IInteger*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createFloatProperty(daqProperty** obj, daqStringObject* name, daqFloatObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createFloatProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IFloat*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createStringProperty(daqProperty** obj, daqStringObject* name, daqStringObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createStringProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IString*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createListProperty(daqProperty** obj, daqStringObject* name, daqListObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createListProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IList*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createDictProperty(daqProperty** obj, daqStringObject* name, daqDictObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createDictProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IDict*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createRatioProperty(daqProperty** obj, daqStringObject* name, daqRatioObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createRatioProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IRatio*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createObjectProperty(daqProperty** obj, daqStringObject* name, daqPropertyObject* defaultValue)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createObjectProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IPropertyObject*>(defaultValue));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createReferenceProperty(daqProperty** obj, daqStringObject* name, daqEvalValue* referencedPropertyEval)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createReferenceProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEvalValue*>(referencedPropertyEval));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createFunctionProperty(daqProperty** obj, daqStringObject* name, daqCallableInfo* callableInfo, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createFunctionProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::ICallableInfo*>(callableInfo), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createSelectionProperty(daqProperty** obj, daqStringObject* name, daqListObject* selectionValues, daqIntegerObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createSelectionProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IList*>(selectionValues), reinterpret_cast<daq::IInteger*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createSparseSelectionProperty(daqProperty** obj, daqStringObject* name, daqDictObject* selectionValues, daqIntegerObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createSparseSelectionProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IDict*>(selectionValues), reinterpret_cast<daq::IInteger*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createStructProperty(daqProperty** obj, daqStringObject* name, daqStructObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createStructProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IStruct*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}

daqErrCode daqProperty_createEnumerationProperty(daqProperty** obj, daqStringObject* name, daqEnumerationObject* defaultValue, daqBooleanObject* visible)
{
    daq::IProperty* ptr = nullptr;
    daqErrCode err = daq::createEnumerationProperty(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(defaultValue), reinterpret_cast<daq::IBoolean*>(visible));
    *obj = reinterpret_cast<daqProperty*>(ptr);
    return err;
}
