//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/property_builder.h>

#include <opendaq/opendaq.h>
#include <coreobjects/property_builder.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROPERTY_BUILDER_INTF_ID = { daq::IPropertyBuilder::Id.Data1, daq::IPropertyBuilder::Id.Data2, daq::IPropertyBuilder::Id.Data3, daq::IPropertyBuilder::Id.Data4_UInt64 };

void daqPropertyBuilder_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PROPERTY_BUILDER_INTF_ID;
}

daqErrCode daqPropertyBuilder_build(daqPropertyBuilder* self, daqProperty** property)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->build(reinterpret_cast<daq::IProperty**>(property));
}

daqErrCode daqPropertyBuilder_setValueType(daqPropertyBuilder* self, daqCoreType type)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setValueType(static_cast<daq::CoreType>(type));
}

daqErrCode daqPropertyBuilder_getValueType(daqPropertyBuilder* self, daqCoreType* type)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getValueType(reinterpret_cast<daq::CoreType*>(type));
}

daqErrCode daqPropertyBuilder_setName(daqPropertyBuilder* self, daqStringObject* name)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setName(reinterpret_cast<daq::IString*>(name));
}

daqErrCode daqPropertyBuilder_getName(daqPropertyBuilder* self, daqStringObject** name)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getName(reinterpret_cast<daq::IString**>(name));
}

daqErrCode daqPropertyBuilder_setDescription(daqPropertyBuilder* self, daqStringObject* description)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setDescription(reinterpret_cast<daq::IString*>(description));
}

daqErrCode daqPropertyBuilder_getDescription(daqPropertyBuilder* self, daqStringObject** description)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getDescription(reinterpret_cast<daq::IString**>(description));
}

daqErrCode daqPropertyBuilder_setUnit(daqPropertyBuilder* self, daqUnit* unit)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setUnit(reinterpret_cast<daq::IUnit*>(unit));
}

daqErrCode daqPropertyBuilder_getUnit(daqPropertyBuilder* self, daqUnit** unit)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getUnit(reinterpret_cast<daq::IUnit**>(unit));
}

daqErrCode daqPropertyBuilder_setMinValue(daqPropertyBuilder* self, daqNumber* min)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setMinValue(reinterpret_cast<daq::INumber*>(min));
}

daqErrCode daqPropertyBuilder_getMinValue(daqPropertyBuilder* self, daqNumber** min)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getMinValue(reinterpret_cast<daq::INumber**>(min));
}

daqErrCode daqPropertyBuilder_setMaxValue(daqPropertyBuilder* self, daqNumber* max)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setMaxValue(reinterpret_cast<daq::INumber*>(max));
}

daqErrCode daqPropertyBuilder_getMaxValue(daqPropertyBuilder* self, daqNumber** max)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getMaxValue(reinterpret_cast<daq::INumber**>(max));
}

daqErrCode daqPropertyBuilder_setDefaultValue(daqPropertyBuilder* self, daqBaseObject* value)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setDefaultValue(reinterpret_cast<daq::IBaseObject*>(value));
}

daqErrCode daqPropertyBuilder_getDefaultValue(daqPropertyBuilder* self, daqBaseObject** value)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getDefaultValue(reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqPropertyBuilder_setSuggestedValues(daqPropertyBuilder* self, daqListObject* values)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setSuggestedValues(reinterpret_cast<daq::IList*>(values));
}

daqErrCode daqPropertyBuilder_getSuggestedValues(daqPropertyBuilder* self, daqListObject** values)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getSuggestedValues(reinterpret_cast<daq::IList**>(values));
}

daqErrCode daqPropertyBuilder_setVisible(daqPropertyBuilder* self, daqBooleanObject* visible)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setVisible(reinterpret_cast<daq::IBoolean*>(visible));
}

daqErrCode daqPropertyBuilder_getVisible(daqPropertyBuilder* self, daqBooleanObject** visible)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getVisible(reinterpret_cast<daq::IBoolean**>(visible));
}

daqErrCode daqPropertyBuilder_setReadOnly(daqPropertyBuilder* self, daqBooleanObject* readOnly)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setReadOnly(reinterpret_cast<daq::IBoolean*>(readOnly));
}

daqErrCode daqPropertyBuilder_getReadOnly(daqPropertyBuilder* self, daqBooleanObject** readOnly)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getReadOnly(reinterpret_cast<daq::IBoolean**>(readOnly));
}

daqErrCode daqPropertyBuilder_setSelectionValues(daqPropertyBuilder* self, daqBaseObject* values)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setSelectionValues(reinterpret_cast<daq::IBaseObject*>(values));
}

daqErrCode daqPropertyBuilder_getSelectionValues(daqPropertyBuilder* self, daqBaseObject** values)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getSelectionValues(reinterpret_cast<daq::IBaseObject**>(values));
}

daqErrCode daqPropertyBuilder_setReferencedProperty(daqPropertyBuilder* self, daqEvalValue* propertyEval)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setReferencedProperty(reinterpret_cast<daq::IEvalValue*>(propertyEval));
}

daqErrCode daqPropertyBuilder_getReferencedProperty(daqPropertyBuilder* self, daqEvalValue** propertyEval)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getReferencedProperty(reinterpret_cast<daq::IEvalValue**>(propertyEval));
}

daqErrCode daqPropertyBuilder_setValidator(daqPropertyBuilder* self, daqValidator* validator)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setValidator(reinterpret_cast<daq::IValidator*>(validator));
}

daqErrCode daqPropertyBuilder_getValidator(daqPropertyBuilder* self, daqValidator** validator)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getValidator(reinterpret_cast<daq::IValidator**>(validator));
}

daqErrCode daqPropertyBuilder_setCoercer(daqPropertyBuilder* self, daqCoercer* coercer)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setCoercer(reinterpret_cast<daq::ICoercer*>(coercer));
}

daqErrCode daqPropertyBuilder_getCoercer(daqPropertyBuilder* self, daqCoercer** coercer)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getCoercer(reinterpret_cast<daq::ICoercer**>(coercer));
}

daqErrCode daqPropertyBuilder_setCallableInfo(daqPropertyBuilder* self, daqCallableInfo* callable)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setCallableInfo(reinterpret_cast<daq::ICallableInfo*>(callable));
}

daqErrCode daqPropertyBuilder_getCallableInfo(daqPropertyBuilder* self, daqCallableInfo** callable)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getCallableInfo(reinterpret_cast<daq::ICallableInfo**>(callable));
}

daqErrCode daqPropertyBuilder_setOnPropertyValueWrite(daqPropertyBuilder* self, daqEvent* event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setOnPropertyValueWrite(reinterpret_cast<daq::IEvent*>(event));
}

daqErrCode daqPropertyBuilder_getOnPropertyValueWrite(daqPropertyBuilder* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getOnPropertyValueWrite(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyBuilder_setOnPropertyValueRead(daqPropertyBuilder* self, daqEvent* event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setOnPropertyValueRead(reinterpret_cast<daq::IEvent*>(event));
}

daqErrCode daqPropertyBuilder_getOnPropertyValueRead(daqPropertyBuilder* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getOnPropertyValueRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyBuilder_setOnSuggestedValuesRead(daqPropertyBuilder* self, daqEvent* event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setOnSuggestedValuesRead(reinterpret_cast<daq::IEvent*>(event));
}

daqErrCode daqPropertyBuilder_getOnSuggestedValuesRead(daqPropertyBuilder* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getOnSuggestedValuesRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyBuilder_setOnSelectionValuesRead(daqPropertyBuilder* self, daqEvent* event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setOnSelectionValuesRead(reinterpret_cast<daq::IEvent*>(event));
}

daqErrCode daqPropertyBuilder_getOnSelectionValuesRead(daqPropertyBuilder* self, daqEvent** event)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getOnSelectionValuesRead(reinterpret_cast<daq::IEvent**>(event));
}

daqErrCode daqPropertyBuilder_setIsIntegerValueSelection(daqPropertyBuilder* self, daqBool isIntegerValueSelection)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->setIsIntegerValueSelection(isIntegerValueSelection);
}

daqErrCode daqPropertyBuilder_getIsIntegerValueSelection(daqPropertyBuilder* self, daqBool* isIntegerValueSelection)
{
    return reinterpret_cast<daq::IPropertyBuilder*>(self)->getIsIntegerValueSelection(isIntegerValueSelection);
}

daqErrCode daqPropertyBuilder_createPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createBoolPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqBooleanObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createBoolPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IBoolean*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createIntPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqIntegerObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createIntPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IInteger*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createFloatPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqFloatObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createFloatPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IFloat*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createStringPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqStringObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createStringPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IString*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createListPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqListObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createListPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IList*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createDictPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqDictObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createDictPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IDict*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createRatioPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqRatioObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createRatioPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IRatio*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createObjectPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqPropertyObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createObjectPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IPropertyObject*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createReferencePropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqEvalValue* referencedPropertyEval)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createReferencePropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEvalValue*>(referencedPropertyEval));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createFunctionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqCallableInfo* callableInfo)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createFunctionPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::ICallableInfo*>(callableInfo));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createSelectionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqListObject* selectionValues, daqIntegerObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createSelectionPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IList*>(selectionValues), reinterpret_cast<daq::IInteger*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createSparseSelectionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqDictObject* selectionValues, daqIntegerObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createSparseSelectionPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IDict*>(selectionValues), reinterpret_cast<daq::IInteger*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createStructPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqStructObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createStructPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IStruct*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}

daqErrCode daqPropertyBuilder_createEnumerationPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqEnumerationObject* defaultValue)
{
    daq::IPropertyBuilder* ptr = nullptr;
    daqErrCode err = daq::createEnumerationPropertyBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IEnumeration*>(defaultValue));
    *obj = reinterpret_cast<daqPropertyBuilder*>(ptr);
    return err;
}
