//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/property_object_core.h>

#include <opendaq/opendaq.h>
#include <coreobjects/property_object_core.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROPERTY_OBJECT_CORE_INTF_ID = { daq::IPropertyObjectCore::Id.Data1, daq::IPropertyObjectCore::Id.Data2, daq::IPropertyObjectCore::Id.Data3, daq::IPropertyObjectCore::Id.Data4_UInt64 };

void daqPropertyObjectCore_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PROPERTY_OBJECT_CORE_INTF_ID;
}

daqErrCode daqPropertyObjectCore_getRecursiveLockGuard(daqPropertyObjectCore* self, daqLockGuard** lockGuard, daqMutex* sync)
{
    return reinterpret_cast<daq::IPropertyObjectCore*>(self)->getRecursiveLockGuard(reinterpret_cast<daq::ILockGuard**>(lockGuard), reinterpret_cast<daq::IMutex*>(sync));
}

daqErrCode daqPropertyObjectCore_getLockGuard(daqPropertyObjectCore* self, daqLockGuard** lockGuard, daqMutex* sync)
{
    return reinterpret_cast<daq::IPropertyObjectCore*>(self)->getLockGuard(reinterpret_cast<daq::ILockGuard**>(lockGuard), reinterpret_cast<daq::IMutex*>(sync));
}

daqErrCode daqPropertyObjectCore_createPropertyObjectCore(daqPropertyObjectCore** obj)
{
    daq::IPropertyObjectCore* ptr = nullptr;
    daqErrCode err = daq::createPropertyObjectCore(&ptr);
    *obj = reinterpret_cast<daqPropertyObjectCore*>(ptr);
    return err;
}
