//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoreobjects/property_metadata_read_args.h>

#include <opendaq/opendaq.h>
#include <coreobjects/property_metadata_read_args.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROPERTY_METADATA_READ_ARGS_INTF_ID = { daq::IPropertyMetadataReadArgs::Id.Data1, daq::IPropertyMetadataReadArgs::Id.Data2, daq::IPropertyMetadataReadArgs::Id.Data3, daq::IPropertyMetadataReadArgs::Id.Data4_UInt64 };

void daqPropertyMetadataReadArgs_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PROPERTY_METADATA_READ_ARGS_INTF_ID;
}

daqErrCode daqPropertyMetadataReadArgs_getProperty(daqPropertyMetadataReadArgs* self, daqProperty** property)
{
    return reinterpret_cast<daq::IPropertyMetadataReadArgs*>(self)->getProperty(reinterpret_cast<daq::IProperty**>(property));
}

daqErrCode daqPropertyMetadataReadArgs_getValue(daqPropertyMetadataReadArgs* self, daqBaseObject** value)
{
    return reinterpret_cast<daq::IPropertyMetadataReadArgs*>(self)->getValue(reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqPropertyMetadataReadArgs_setValue(daqPropertyMetadataReadArgs* self, daqBaseObject* value)
{
    return reinterpret_cast<daq::IPropertyMetadataReadArgs*>(self)->setValue(reinterpret_cast<daq::IBaseObject*>(value));
}

daqErrCode daqPropertyMetadataReadArgs_createPropertyMetadataReadArgs(daqPropertyMetadataReadArgs** obj, daqProperty* prop)
{
    daq::IPropertyMetadataReadArgs* ptr = nullptr;
    daqErrCode err = daq::createPropertyMetadataReadArgs(&ptr, reinterpret_cast<daq::IProperty*>(prop));
    *obj = reinterpret_cast<daqPropertyMetadataReadArgs*>(ptr);
    return err;
}
