//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqDeviceUpdateOptions daqDeviceUpdateOptions;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqListObject daqListObject;

    EXPORTED extern const daqIntfID DAQ_DEVICE_UPDATE_OPTIONS_INTF_ID;
    void EXPORTED daqDeviceUpdateOptions_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqDeviceUpdateOptions_getLocalId(daqDeviceUpdateOptions* self, daqStringObject** localId);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getManufacturer(daqDeviceUpdateOptions* self, daqStringObject** manufacturer);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getSerialNumber(daqDeviceUpdateOptions* self, daqStringObject** serialNumber);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getConnectionString(daqDeviceUpdateOptions* self, daqStringObject** connectionString);
    daqErrCode EXPORTED daqDeviceUpdateOptions_setNewManufacturer(daqDeviceUpdateOptions* self, daqStringObject* manufacturer);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getNewManufacturer(daqDeviceUpdateOptions* self, daqStringObject** manufacturer);
    daqErrCode EXPORTED daqDeviceUpdateOptions_setNewSerialNumber(daqDeviceUpdateOptions* self, daqStringObject* serialNumber);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getNewSerialNumber(daqDeviceUpdateOptions* self, daqStringObject** serialNumber);
    daqErrCode EXPORTED daqDeviceUpdateOptions_setNewConnectionString(daqDeviceUpdateOptions* self, daqStringObject* connectionString);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getNewConnectionString(daqDeviceUpdateOptions* self, daqStringObject** connectionString);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getUpdateMode(daqDeviceUpdateOptions* self, daqDeviceUpdateMode* mode);
    daqErrCode EXPORTED daqDeviceUpdateOptions_setUpdateMode(daqDeviceUpdateOptions* self, daqDeviceUpdateMode mode);
    daqErrCode EXPORTED daqDeviceUpdateOptions_getChildDeviceOptions(daqDeviceUpdateOptions* self, daqListObject** childDeviceOptions);
    daqErrCode EXPORTED daqDeviceUpdateOptions_createDeviceUpdateOptions(daqDeviceUpdateOptions** obj, daqStringObject* setupString);

#ifdef __cplusplus
}
#endif
