//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqBooleanObject daqBooleanObject;

    EXPORTED extern const daqIntfID DAQ_BOOLEAN_INTF_ID;
    void EXPORTED daqBoolean_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqBoolean_getValue(daqBooleanObject* self, daqBool* value);
    daqErrCode EXPORTED daqBoolean_equalsValue(daqBooleanObject* self, daqBool value, daqBool* equal);
    daqErrCode EXPORTED daqBoolean_createBoolean(daqBooleanObject** obj, daqBool value);
    daqErrCode EXPORTED daqBoolean_createBoolObject(daqBooleanObject** obj, daqBool value);

#ifdef __cplusplus
}
#endif
