//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqDictObject daqDictObject;
    typedef struct daqListObject daqListObject;
    typedef struct daqIterable daqIterable;

    EXPORTED extern const daqIntfID DAQ_DICT_INTF_ID;
    void EXPORTED daqDict_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqDict_get(daqDictObject* self, daqBaseObject* key, daqBaseObject** value);
    daqErrCode EXPORTED daqDict_set(daqDictObject* self, daqBaseObject* key, daqBaseObject* value);
    daqErrCode EXPORTED daqDict_remove(daqDictObject* self, daqBaseObject* key, daqBaseObject** value);
    daqErrCode EXPORTED daqDict_deleteItem(daqDictObject* self, daqBaseObject* key);
    daqErrCode EXPORTED daqDict_clear(daqDictObject* self);
    daqErrCode EXPORTED daqDict_getCount(daqDictObject* self, daqSizeT* size);
    daqErrCode EXPORTED daqDict_hasKey(daqDictObject* self, daqBaseObject* key, daqBool* hasKey);
    daqErrCode EXPORTED daqDict_getKeyList(daqDictObject* self, daqListObject** keys);
    daqErrCode EXPORTED daqDict_getValueList(daqDictObject* self, daqListObject** values);
    daqErrCode EXPORTED daqDict_getKeys(daqDictObject* self, daqIterable** iterable);
    daqErrCode EXPORTED daqDict_getValues(daqDictObject* self, daqIterable** iterable);
    daqErrCode EXPORTED daqDict_createDict(daqDictObject** obj);
    daqErrCode EXPORTED daqDict_createDictWithExpectedTypes(daqDictObject** obj, daqIntfID keyType, daqIntfID valueType);

#ifdef __cplusplus
}
#endif
