//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:49.
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqErrorInfo daqErrorInfo;
    typedef struct daqString daqString;
    typedef struct daqList daqList;

    EXPORTED extern const daqIntfID DAQ_ERROR_INFO_INTF_ID;

    daqErrCode EXPORTED daqErrorInfo_setMessage(daqErrorInfo* self, daqString* message);
    daqErrCode EXPORTED daqErrorInfo_getMessage(daqErrorInfo* self, daqString** message);
    daqErrCode EXPORTED daqErrorInfo_setSource(daqErrorInfo* self, daqString* source);
    daqErrCode EXPORTED daqErrorInfo_getSource(daqErrorInfo* self, daqString** source);
    daqErrCode EXPORTED daqErrorInfo_setFileName(daqErrorInfo* self, daqCConstCharPtr fileName);
    daqErrCode EXPORTED daqErrorInfo_getFileName(daqErrorInfo* self, daqCConstCharPtr* fileName);
    daqErrCode EXPORTED daqErrorInfo_setFileLine(daqErrorInfo* self, daqCInt fileLine);
    daqErrCode EXPORTED daqErrorInfo_getFileLine(daqErrorInfo* self, daqCInt* fileLine);
    daqErrCode EXPORTED daqErrorInfo_setErrorCode(daqErrorInfo* self, daqErrCode errorCode);
    daqErrCode EXPORTED daqErrorInfo_getErrorCode(daqErrorInfo* self, daqErrCode* errorCode);
    daqErrCode EXPORTED daqErrorInfo_setPreviousErrorCode(daqErrorInfo* self, daqErrCode prevErrCode);
    daqErrCode EXPORTED daqErrorInfo_getPreviousErrorCode(daqErrorInfo* self, daqErrCode* prevErrCode);
    daqErrCode EXPORTED daqErrorInfo_getFormattedMessage(daqErrorInfo* self, daqString** message);
    daqErrCode EXPORTED daqErrorInfo_createErrorInfo(daqErrorInfo** obj);

    /* The error info attached to the calling thread. These wrap the global functions of the same purpose
       in the core, which are not exported by this library. */
    void EXPORTED daqErrorInfo_set(daqErrorInfo* errorInfo);
    void EXPORTED daqErrorInfo_extend(daqErrorInfo* errorInfo);
    void EXPORTED daqErrorInfo_get(daqErrorInfo** errorInfo);
    void EXPORTED daqErrorInfo_clear(void);
    void EXPORTED daqErrorInfo_getList(daqList** errorInfoList);
    daqErrCode EXPORTED daqErrorInfo_getMessageForThread(daqString** errorMessage);

#ifdef __cplusplus
}
#endif
