//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqSerializedObject daqSerializedObject;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqSerializedList daqSerializedList;
    typedef struct daqFunctionObject daqFunctionObject;
    typedef struct daqListObject daqListObject;

    EXPORTED extern const daqIntfID DAQ_SERIALIZED_OBJECT_INTF_ID;
    void EXPORTED daqSerializedObject_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqSerializedObject_readSerializedObject(daqSerializedObject* self, daqStringObject* key, daqSerializedObject** plainObj);
    daqErrCode EXPORTED daqSerializedObject_readSerializedList(daqSerializedObject* self, daqStringObject* key, daqSerializedList** list);
    daqErrCode EXPORTED daqSerializedObject_readList(daqSerializedObject* self, daqStringObject* key, daqBaseObject* context, daqFunctionObject* factoryCallback, daqListObject** list);
    daqErrCode EXPORTED daqSerializedObject_readObject(daqSerializedObject* self, daqStringObject* key, daqBaseObject* context, daqFunctionObject* factoryCallback, daqBaseObject** obj);
    daqErrCode EXPORTED daqSerializedObject_readString(daqSerializedObject* self, daqStringObject* key, daqStringObject** string);
    daqErrCode EXPORTED daqSerializedObject_readBool(daqSerializedObject* self, daqStringObject* key, daqBool* boolean);
    daqErrCode EXPORTED daqSerializedObject_readFloat(daqSerializedObject* self, daqStringObject* key, daqFloat* real);
    daqErrCode EXPORTED daqSerializedObject_readInt(daqSerializedObject* self, daqStringObject* key, daqInt* integer);
    daqErrCode EXPORTED daqSerializedObject_hasKey(daqSerializedObject* self, daqStringObject* key, daqBool* hasKey);
    daqErrCode EXPORTED daqSerializedObject_getKeys(daqSerializedObject* self, daqListObject** list);
    daqErrCode EXPORTED daqSerializedObject_getType(daqSerializedObject* self, daqStringObject* key, daqCoreType* type);
    daqErrCode EXPORTED daqSerializedObject_isRoot(daqSerializedObject* self, daqBool* isRoot);
    daqErrCode EXPORTED daqSerializedObject_toJson(daqSerializedObject* self, daqStringObject** jsonString);

#ifdef __cplusplus
}
#endif
