//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqStructBuilder daqStructBuilder;
    typedef struct daqStructObject daqStructObject;
    typedef struct daqStructType daqStructType;
    typedef struct daqListObject daqListObject;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqTypeManager daqTypeManager;

    EXPORTED extern const daqIntfID DAQ_STRUCT_BUILDER_INTF_ID;
    void EXPORTED daqStructBuilder_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqStructBuilder_build(daqStructBuilder* self, daqStructObject** struct_);
    daqErrCode EXPORTED daqStructBuilder_getStructType(daqStructBuilder* self, daqStructType** type);
    daqErrCode EXPORTED daqStructBuilder_getFieldNames(daqStructBuilder* self, daqListObject** names);
    daqErrCode EXPORTED daqStructBuilder_setFieldValues(daqStructBuilder* self, daqListObject* values);
    daqErrCode EXPORTED daqStructBuilder_getFieldValues(daqStructBuilder* self, daqListObject** values);
    daqErrCode EXPORTED daqStructBuilder_set(daqStructBuilder* self, daqStringObject* name, daqBaseObject* field);
    daqErrCode EXPORTED daqStructBuilder_get(daqStructBuilder* self, daqStringObject* name, daqBaseObject** field);
    daqErrCode EXPORTED daqStructBuilder_hasField(daqStructBuilder* self, daqStringObject* name, daqBool* contains);
    daqErrCode EXPORTED daqStructBuilder_getAsDictionary(daqStructBuilder* self, daqDictObject** dictionary);
    daqErrCode EXPORTED daqStructBuilder_createStructBuilder(daqStructBuilder** obj, daqStringObject* name, daqTypeManager* typeManager);
    daqErrCode EXPORTED daqStructBuilder_createStructBuilderFromStruct(daqStructBuilder** obj, daqStructObject* struct_);

#ifdef __cplusplus
}
#endif
