//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqWeakRef daqWeakRef;
    typedef struct daqSupportsWeakRef daqSupportsWeakRef;

    EXPORTED extern const daqIntfID DAQ_WEAK_REF_INTF_ID;
    void EXPORTED daqWeakRef_getInterfaceId(daqIntfID* intfId);
    EXPORTED extern const daqIntfID DAQ_SUPPORTS_WEAK_REF_INTF_ID;
    void EXPORTED daqSupportsWeakRef_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqWeakRef_getRef(daqWeakRef* self, daqBaseObject** object);
    daqErrCode EXPORTED daqWeakRef_getRefAs(daqWeakRef* self, daqIntfID intfID, void** object);
    daqErrCode EXPORTED daqSupportsWeakRef_getWeakRef(daqSupportsWeakRef* self, daqWeakRef** weakRef);

#ifdef __cplusplus
}
#endif
