//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/complex_number.h>

#include <opendaq/opendaq.h>
#include <coretypes/complex_number.h>

#include <copendaq_private.h>

const daqIntfID DAQ_COMPLEX_NUMBER_INTF_ID = { daq::IComplexNumber::Id.Data1, daq::IComplexNumber::Id.Data2, daq::IComplexNumber::Id.Data3, daq::IComplexNumber::Id.Data4_UInt64 };

void daqComplexNumber_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_COMPLEX_NUMBER_INTF_ID;
}

daqErrCode daqComplexNumber_getValue(daqComplexNumber* self, daqComplexFloat64* value)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getValue(reinterpret_cast<daq::ComplexFloat64*>(value));
}

daqErrCode daqComplexNumber_equalsValue(daqComplexNumber* self, daqComplexFloat64 value, daqCBool* equal)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->equalsValue(copendaq::utils::toDaqComplexFloat64(value), equal);
}

daqErrCode daqComplexNumber_getReal(daqComplexNumber* self, daqCFloat* real)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getReal(real);
}

daqErrCode daqComplexNumber_getImaginary(daqComplexNumber* self, daqCFloat* imaginary)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getImaginary(imaginary);
}

daqErrCode daqComplexNumber_createComplexNumber(daqComplexNumber** obj, daqCFloat real, daqCFloat imaginary)
{
    daq::IComplexNumber* ptr = nullptr;
    daqErrCode err = daq::createComplexNumber(&ptr, real, imaginary);
    *obj = reinterpret_cast<daqComplexNumber*>(ptr);
    return err;
}
