//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/complex_number.h>

#include <opendaq/opendaq.h>
#include <coretypes/complex_number.h>

#include <copendaq_private.h>

const daqIntfID DAQ_COMPLEX_NUMBER_INTF_ID = { daq::IComplexNumber::Id.Data1, daq::IComplexNumber::Id.Data2, daq::IComplexNumber::Id.Data3, daq::IComplexNumber::Id.Data4_UInt64 };

void daqComplexNumber_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_COMPLEX_NUMBER_INTF_ID;
}

/*
daqErrCode daqComplexNumber_getValue(daqComplexNumberObject* self, daqComplexFloat64* value)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getValue(reinterpret_cast<daq::ComplexFloat64*>(value));
}
*/

/*
daqErrCode daqComplexNumber_equalsValue(daqComplexNumberObject* self, daqComplexFloat64 value, daqBool* equal)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->equalsValue(static_cast<daq::ComplexFloat64>(value), equal);
}
*/

daqErrCode daqComplexNumber_getReal(daqComplexNumberObject* self, daqFloat* real)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getReal(real);
}

daqErrCode daqComplexNumber_getImaginary(daqComplexNumberObject* self, daqFloat* imaginary)
{
    return reinterpret_cast<daq::IComplexNumber*>(self)->getImaginary(imaginary);
}

daqErrCode daqComplexNumber_createComplexNumber(daqComplexNumberObject** obj, daqFloat real, daqFloat imaginary)
{
    daq::IComplexNumber* ptr = nullptr;
    daqErrCode err = daq::createComplexNumber(&ptr, real, imaginary);
    *obj = reinterpret_cast<daqComplexNumberObject*>(ptr);
    return err;
}
