//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/deserializer.h>

#include <opendaq/opendaq.h>
#include <coretypes/deserializer.h>

#include <copendaq_private.h>

const daqIntfID DAQ_DESERIALIZER_INTF_ID = { daq::IDeserializer::Id.Data1, daq::IDeserializer::Id.Data2, daq::IDeserializer::Id.Data3, daq::IDeserializer::Id.Data4_UInt64 };

void daqDeserializer_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_DESERIALIZER_INTF_ID;
}

daqErrCode daqDeserializer_deserialize(daqDeserializer* self, daqStringObject* serialized, daqBaseObject* context, daqFunctionObject* factoryCallback, daqBaseObject** object)
{
    return reinterpret_cast<daq::IDeserializer*>(self)->deserialize(reinterpret_cast<daq::IString*>(serialized), reinterpret_cast<daq::IBaseObject*>(context), reinterpret_cast<daq::IFunction*>(factoryCallback), reinterpret_cast<daq::IBaseObject**>(object));
}

daqErrCode daqDeserializer_update(daqDeserializer* self, daqUpdatable* updatable, daqStringObject* serialized, daqBaseObject* config)
{
    return reinterpret_cast<daq::IDeserializer*>(self)->update(reinterpret_cast<daq::IUpdatable*>(updatable), reinterpret_cast<daq::IString*>(serialized), reinterpret_cast<daq::IBaseObject*>(config));
}

daqErrCode daqDeserializer_callCustomProc(daqDeserializer* self, daqProcedureObject* customDeserialize, daqStringObject* serialized)
{
    return reinterpret_cast<daq::IDeserializer*>(self)->callCustomProc(reinterpret_cast<daq::IProcedure*>(customDeserialize), reinterpret_cast<daq::IString*>(serialized));
}
