//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/development_version_info.h>

#include <opendaq/opendaq.h>
#include <coretypes/development_version_info.h>

#include <copendaq_private.h>

const daqIntfID DAQ_DEVELOPMENT_VERSION_INFO_INTF_ID = { daq::IDevelopmentVersionInfo::Id.Data1, daq::IDevelopmentVersionInfo::Id.Data2, daq::IDevelopmentVersionInfo::Id.Data3, daq::IDevelopmentVersionInfo::Id.Data4_UInt64 };

void daqDevelopmentVersionInfo_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_DEVELOPMENT_VERSION_INFO_INTF_ID;
}

daqErrCode daqDevelopmentVersionInfo_getMajor(daqDevelopmentVersionInfo* self, daqSizeT* major)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getMajor(major);
}

daqErrCode daqDevelopmentVersionInfo_getMinor(daqDevelopmentVersionInfo* self, daqSizeT* minor)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getMinor(minor);
}

daqErrCode daqDevelopmentVersionInfo_getPatch(daqDevelopmentVersionInfo* self, daqSizeT* patch)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getPatch(patch);
}

daqErrCode daqDevelopmentVersionInfo_getTweak(daqDevelopmentVersionInfo* self, daqSizeT* tweak)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getTweak(tweak);
}

daqErrCode daqDevelopmentVersionInfo_getBranchName(daqDevelopmentVersionInfo* self, daqString** branchName)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getBranchName(reinterpret_cast<daq::IString**>(branchName));
}

daqErrCode daqDevelopmentVersionInfo_getHashDigest(daqDevelopmentVersionInfo* self, daqString** hash)
{
    return reinterpret_cast<daq::IDevelopmentVersionInfo*>(self)->getHashDigest(reinterpret_cast<daq::IString**>(hash));
}

daqErrCode daqDevelopmentVersionInfo_createDevelopmentVersionInfo(daqDevelopmentVersionInfo** obj, daqSizeT major, daqSizeT minor, daqSizeT patch, daqSizeT tweak, daqString* branch, daqString* hash)
{
    daq::IDevelopmentVersionInfo* ptr = nullptr;
    daqErrCode err = daq::createDevelopmentVersionInfo(&ptr, major, minor, patch, tweak, reinterpret_cast<daq::IString*>(branch), reinterpret_cast<daq::IString*>(hash));
    *obj = reinterpret_cast<daqDevelopmentVersionInfo*>(ptr);
    return err;
}
