//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/dictobject.h>

#include <opendaq/opendaq.h>
#include <coretypes/dictobject.h>

#include <copendaq_private.h>

const daqIntfID DAQ_DICT_INTF_ID = { daq::IDict::Id.Data1, daq::IDict::Id.Data2, daq::IDict::Id.Data3, daq::IDict::Id.Data4_UInt64 };

void daqDict_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_DICT_INTF_ID;
}

daqErrCode daqDict_get(daqDictObject* self, daqBaseObject* key, daqBaseObject** value)
{
    return reinterpret_cast<daq::IDict*>(self)->get(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqDict_set(daqDictObject* self, daqBaseObject* key, daqBaseObject* value)
{
    return reinterpret_cast<daq::IDict*>(self)->set(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject*>(value));
}

daqErrCode daqDict_remove(daqDictObject* self, daqBaseObject* key, daqBaseObject** value)
{
    return reinterpret_cast<daq::IDict*>(self)->remove(reinterpret_cast<daq::IBaseObject*>(key), reinterpret_cast<daq::IBaseObject**>(value));
}

daqErrCode daqDict_deleteItem(daqDictObject* self, daqBaseObject* key)
{
    return reinterpret_cast<daq::IDict*>(self)->deleteItem(reinterpret_cast<daq::IBaseObject*>(key));
}

daqErrCode daqDict_clear(daqDictObject* self)
{
    return reinterpret_cast<daq::IDict*>(self)->clear();
}

daqErrCode daqDict_getCount(daqDictObject* self, daqSizeT* size)
{
    return reinterpret_cast<daq::IDict*>(self)->getCount(size);
}

daqErrCode daqDict_hasKey(daqDictObject* self, daqBaseObject* key, daqBool* hasKey)
{
    return reinterpret_cast<daq::IDict*>(self)->hasKey(reinterpret_cast<daq::IBaseObject*>(key), hasKey);
}

daqErrCode daqDict_getKeyList(daqDictObject* self, daqListObject** keys)
{
    return reinterpret_cast<daq::IDict*>(self)->getKeyList(reinterpret_cast<daq::IList**>(keys));
}

daqErrCode daqDict_getValueList(daqDictObject* self, daqListObject** values)
{
    return reinterpret_cast<daq::IDict*>(self)->getValueList(reinterpret_cast<daq::IList**>(values));
}

daqErrCode daqDict_getKeys(daqDictObject* self, daqIterable** iterable)
{
    return reinterpret_cast<daq::IDict*>(self)->getKeys(reinterpret_cast<daq::IIterable**>(iterable));
}

daqErrCode daqDict_getValues(daqDictObject* self, daqIterable** iterable)
{
    return reinterpret_cast<daq::IDict*>(self)->getValues(reinterpret_cast<daq::IIterable**>(iterable));
}

daqErrCode daqDict_createDict(daqDictObject** obj)
{
    daq::IDict* ptr = nullptr;
    daqErrCode err = daq::createDict(&ptr);
    *obj = reinterpret_cast<daqDictObject*>(ptr);
    return err;
}

daqErrCode daqDict_createDictWithExpectedTypes(daqDictObject** obj, daqIntfID keyType, daqIntfID valueType)
{
    daq::IDict* ptr = nullptr;
    daqErrCode err = daq::createDictWithExpectedTypes(&ptr, copendaq::utils::toDaqIntfId(keyType), copendaq::utils::toDaqIntfId(valueType));
    *obj = reinterpret_cast<daqDictObject*>(ptr);
    return err;
}
