//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/enumeration.h>

#include <opendaq/opendaq.h>
#include <coretypes/enumeration.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ENUMERATION_INTF_ID = { daq::IEnumeration::Id.Data1, daq::IEnumeration::Id.Data2, daq::IEnumeration::Id.Data3, daq::IEnumeration::Id.Data4_UInt64 };

void daqEnumeration_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_ENUMERATION_INTF_ID;
}

daqErrCode daqEnumeration_getEnumerationType(daqEnumerationObject* self, daqEnumerationType** type)
{
    return reinterpret_cast<daq::IEnumeration*>(self)->getEnumerationType(reinterpret_cast<daq::IEnumerationType**>(type));
}

daqErrCode daqEnumeration_getValue(daqEnumerationObject* self, daqStringObject** value)
{
    return reinterpret_cast<daq::IEnumeration*>(self)->getValue(reinterpret_cast<daq::IString**>(value));
}

daqErrCode daqEnumeration_getIntValue(daqEnumerationObject* self, daqInt* value)
{
    return reinterpret_cast<daq::IEnumeration*>(self)->getIntValue(value);
}

daqErrCode daqEnumeration_createEnumeration(daqEnumerationObject** obj, daqStringObject* name, daqStringObject* value, daqTypeManager* typeManager)
{
    daq::IEnumeration* ptr = nullptr;
    daqErrCode err = daq::createEnumeration(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IString*>(value), reinterpret_cast<daq::ITypeManager*>(typeManager));
    *obj = reinterpret_cast<daqEnumerationObject*>(ptr);
    return err;
}

daqErrCode daqEnumeration_createEnumerationWithIntValue(daqEnumerationObject** obj, daqStringObject* name, daqIntegerObject* value, daqTypeManager* typeManager)
{
    daq::IEnumeration* ptr = nullptr;
    daqErrCode err = daq::createEnumerationWithIntValue(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IInteger*>(value), reinterpret_cast<daq::ITypeManager*>(typeManager));
    *obj = reinterpret_cast<daqEnumerationObject*>(ptr);
    return err;
}

daqErrCode daqEnumeration_createEnumerationWithType(daqEnumerationObject** obj, daqEnumerationType* type, daqStringObject* value)
{
    daq::IEnumeration* ptr = nullptr;
    daqErrCode err = daq::createEnumerationWithType(&ptr, reinterpret_cast<daq::IEnumerationType*>(type), reinterpret_cast<daq::IString*>(value));
    *obj = reinterpret_cast<daqEnumerationObject*>(ptr);
    return err;
}

daqErrCode daqEnumeration_createEnumerationWithIntValueAndType(daqEnumerationObject** obj, daqEnumerationType* type, daqIntegerObject* value)
{
    daq::IEnumeration* ptr = nullptr;
    daqErrCode err = daq::createEnumerationWithIntValueAndType(&ptr, reinterpret_cast<daq::IEnumerationType*>(type), reinterpret_cast<daq::IInteger*>(value));
    *obj = reinterpret_cast<daqEnumerationObject*>(ptr);
    return err;
}
