//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/enumeration_type.h>

#include <opendaq/opendaq.h>
#include <coretypes/enumeration_type.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ENUMERATION_TYPE_INTF_ID = { daq::IEnumerationType::Id.Data1, daq::IEnumerationType::Id.Data2, daq::IEnumerationType::Id.Data3, daq::IEnumerationType::Id.Data4_UInt64 };

void daqEnumerationType_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_ENUMERATION_TYPE_INTF_ID;
}

daqErrCode daqEnumerationType_getEnumeratorNames(daqEnumerationType* self, daqListObject** names)
{
    return reinterpret_cast<daq::IEnumerationType*>(self)->getEnumeratorNames(reinterpret_cast<daq::IList**>(names));
}

daqErrCode daqEnumerationType_getAsDictionary(daqEnumerationType* self, daqDictObject** dictionary)
{
    return reinterpret_cast<daq::IEnumerationType*>(self)->getAsDictionary(reinterpret_cast<daq::IDict**>(dictionary));
}

daqErrCode daqEnumerationType_getEnumeratorIntValue(daqEnumerationType* self, daqStringObject* name, daqInt* value)
{
    return reinterpret_cast<daq::IEnumerationType*>(self)->getEnumeratorIntValue(reinterpret_cast<daq::IString*>(name), value);
}

daqErrCode daqEnumerationType_getCount(daqEnumerationType* self, daqSizeT* count)
{
    return reinterpret_cast<daq::IEnumerationType*>(self)->getCount(count);
}

daqErrCode daqEnumerationType_createEnumerationType(daqEnumerationType** obj, daqStringObject* typeName, daqListObject* enumeratorNames, daqInt firstEnumeratorIntValue)
{
    daq::IEnumerationType* ptr = nullptr;
    daqErrCode err = daq::createEnumerationType(&ptr, reinterpret_cast<daq::IString*>(typeName), reinterpret_cast<daq::IList*>(enumeratorNames), firstEnumeratorIntValue);
    *obj = reinterpret_cast<daqEnumerationType*>(ptr);
    return err;
}

daqErrCode daqEnumerationType_createEnumerationTypeWithValues(daqEnumerationType** obj, daqStringObject* typeName, daqDictObject* enumerators)
{
    daq::IEnumerationType* ptr = nullptr;
    daqErrCode err = daq::createEnumerationTypeWithValues(&ptr, reinterpret_cast<daq::IString*>(typeName), reinterpret_cast<daq::IDict*>(enumerators));
    *obj = reinterpret_cast<daqEnumerationType*>(ptr);
    return err;
}
