//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0) on 03.06.2025 17:17:49.
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/errorinfo.h>

#include <opendaq/opendaq.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ERROR_INFO_INTF_ID = { daq::IErrorInfo::Id.Data1, daq::IErrorInfo::Id.Data2, daq::IErrorInfo::Id.Data3, daq::IErrorInfo::Id.Data4_UInt64 };

daqErrCode daqErrorInfo_setMessage(daqErrorInfo* self, daqString* message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setMessage(reinterpret_cast<daq::IString*>(message));
}

daqErrCode daqErrorInfo_getMessage(daqErrorInfo* self, daqString** message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getMessage(reinterpret_cast<daq::IString**>(message));
}

daqErrCode daqErrorInfo_setSource(daqErrorInfo* self, daqString* source)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setSource(reinterpret_cast<daq::IString*>(source));
}

daqErrCode daqErrorInfo_getSource(daqErrorInfo* self, daqString** source)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getSource(reinterpret_cast<daq::IString**>(source));
}

daqErrCode daqErrorInfo_setFileName(daqErrorInfo* self, daqCConstCharPtr fileName)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setFileName(static_cast<daq::ConstCharPtr>(fileName));
}

daqErrCode daqErrorInfo_getFileName(daqErrorInfo* self, daqCConstCharPtr* fileName)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFileName(reinterpret_cast<daq::ConstCharPtr*>(fileName));
}

daqErrCode daqErrorInfo_setFileLine(daqErrorInfo* self, daqCInt fileLine)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setFileLine(fileLine);
}

daqErrCode daqErrorInfo_getFileLine(daqErrorInfo* self, daqCInt* fileLine)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFileLine(fileLine);
}

daqErrCode daqErrorInfo_createErrorInfo(daqErrorInfo** obj)
{
    daq::IErrorInfo* ptr = nullptr;
    daqErrCode err = daq::createErrorInfo(&ptr);
    *obj = reinterpret_cast<daqErrorInfo*>(ptr);
    return err;
}

daqErrCode daqErrorInfo_setErrorCode(daqErrorInfo* self, daqErrCode errorCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setErrorCode(errorCode);
}

daqErrCode daqErrorInfo_getErrorCode(daqErrorInfo* self, daqErrCode* errorCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getErrorCode(errorCode);
}

daqErrCode daqErrorInfo_setPreviousErrorCode(daqErrorInfo* self, daqErrCode prevErrCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setPreviousErrorCode(prevErrCode);
}

daqErrCode daqErrorInfo_getPreviousErrorCode(daqErrorInfo* self, daqErrCode* prevErrCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getPreviousErrorCode(prevErrCode);
}

daqErrCode daqErrorInfo_getFormattedMessage(daqErrorInfo* self, daqString** message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFormattedMessage(reinterpret_cast<daq::IString**>(message));
}

void daqErrorInfo_set(daqErrorInfo* errorInfo)
{
    daqSetErrorInfo(reinterpret_cast<daq::IErrorInfo*>(errorInfo));
}

void daqErrorInfo_extend(daqErrorInfo* errorInfo)
{
    daqExtendErrorInfo(reinterpret_cast<daq::IErrorInfo*>(errorInfo));
}

void daqErrorInfo_get(daqErrorInfo** errorInfo)
{
    daqGetErrorInfo(reinterpret_cast<daq::IErrorInfo**>(errorInfo));
}

void daqErrorInfo_clear()
{
    daqClearErrorInfo();
}

void daqErrorInfo_getList(daqList** errorInfoList)
{
    daqGetErrorInfoList(reinterpret_cast<daq::IList**>(errorInfoList));
}

daqErrCode daqErrorInfo_getMessageForThread(daqString** errorMessage)
{
    return daqGetErrorInfoMessage(reinterpret_cast<daq::IString**>(errorMessage));
}
