//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/errorinfo.h>

#include <opendaq/opendaq.h>
#include <coretypes/errorinfo.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ERROR_INFO_INTF_ID = { daq::IErrorInfo::Id.Data1, daq::IErrorInfo::Id.Data2, daq::IErrorInfo::Id.Data3, daq::IErrorInfo::Id.Data4_UInt64 };

void daqErrorInfo_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_ERROR_INFO_INTF_ID;
}

daqErrCode daqErrorInfo_setMessage(daqErrorInfo* self, daqStringObject* message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setMessage(reinterpret_cast<daq::IString*>(message));
}

daqErrCode daqErrorInfo_getMessage(daqErrorInfo* self, daqStringObject** message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getMessage(reinterpret_cast<daq::IString**>(message));
}

daqErrCode daqErrorInfo_setSource(daqErrorInfo* self, daqStringObject* source)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setSource(reinterpret_cast<daq::IString*>(source));
}

daqErrCode daqErrorInfo_getSource(daqErrorInfo* self, daqStringObject** source)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getSource(reinterpret_cast<daq::IString**>(source));
}

daqErrCode daqErrorInfo_setFileName(daqErrorInfo* self, daqConstCharPtr fileName)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setFileName(static_cast<daq::ConstCharPtr>(fileName));
}

daqErrCode daqErrorInfo_getFileName(daqErrorInfo* self, daqConstCharPtr* fileName)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFileName(reinterpret_cast<daq::ConstCharPtr*>(fileName));
}

daqErrCode daqErrorInfo_setFileLine(daqErrorInfo* self, daqInt fileLine)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setFileLine(fileLine);
}

daqErrCode daqErrorInfo_getFileLine(daqErrorInfo* self, daqInt* fileLine)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFileLine(fileLine);
}

daqErrCode daqErrorInfo_setErrorCode(daqErrorInfo* self, daqErrCode errorCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setErrorCode(static_cast<daq::ErrCode>(errorCode));
}

daqErrCode daqErrorInfo_getErrorCode(daqErrorInfo* self, daqErrCode* errorCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getErrorCode(reinterpret_cast<daq::ErrCode*>(errorCode));
}

daqErrCode daqErrorInfo_setPreviousErrorCode(daqErrorInfo* self, daqErrCode prevErrCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->setPreviousErrorCode(static_cast<daq::ErrCode>(prevErrCode));
}

daqErrCode daqErrorInfo_getPreviousErrorCode(daqErrorInfo* self, daqErrCode* prevErrCode)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getPreviousErrorCode(reinterpret_cast<daq::ErrCode*>(prevErrCode));
}

daqErrCode daqErrorInfo_getFormattedMessage(daqErrorInfo* self, daqStringObject** message)
{
    return reinterpret_cast<daq::IErrorInfo*>(self)->getFormattedMessage(reinterpret_cast<daq::IString**>(message));
}

daqErrCode daqErrorInfo_createErrorInfo(daqErrorInfo** obj)
{
    daq::IErrorInfo* ptr = nullptr;
    daqErrCode err = daq::createErrorInfo(&ptr);
    *obj = reinterpret_cast<daqErrorInfo*>(ptr);
    return err;
}
