//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/error_guard.h>

#include <opendaq/opendaq.h>
#include <coretypes/error_guard.h>

#include <copendaq_private.h>

const daqIntfID DAQ_ERROR_GUARD_INTF_ID = { daq::IErrorGuard::Id.Data1, daq::IErrorGuard::Id.Data2, daq::IErrorGuard::Id.Data3, daq::IErrorGuard::Id.Data4_UInt64 };

void daqErrorGuard_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_ERROR_GUARD_INTF_ID;
}

daqErrCode daqErrorGuard_getFormattedMessage(daqErrorGuard* self, daqString** message)
{
    return reinterpret_cast<daq::IErrorGuard*>(self)->getFormattedMessage(reinterpret_cast<daq::IString**>(message));
}

daqErrCode daqErrorGuard_getLastErrorInfo(daqErrorGuard* self, daqErrorInfo** errorInfo)
{
    return reinterpret_cast<daq::IErrorGuard*>(self)->getLastErrorInfo(reinterpret_cast<daq::IErrorInfo**>(errorInfo));
}

daqErrCode daqErrorGuard_getErrorInfoList(daqErrorGuard* self, daqList** errorInfos)
{
    return reinterpret_cast<daq::IErrorGuard*>(self)->getErrorInfoList(reinterpret_cast<daq::IList**>(errorInfos));
}

daqErrCode daqErrorGuard_createErrorGuard(daqErrorGuard** obj, daqCConstCharPtr fileName, daqCInt fileLine)
{
    daq::IErrorGuard* ptr = nullptr;
    daqErrCode err = daq::createErrorGuard(&ptr, static_cast<daq::ConstCharPtr>(fileName), fileLine);
    *obj = reinterpret_cast<daqErrorGuard*>(ptr);
    return err;
}
