//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/float.h>

#include <opendaq/opendaq.h>
#include <coretypes/float.h>

#include <copendaq_private.h>

const daqIntfID DAQ_FLOAT_INTF_ID = { daq::IFloat::Id.Data1, daq::IFloat::Id.Data2, daq::IFloat::Id.Data3, daq::IFloat::Id.Data4_UInt64 };

void daqFloat_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_FLOAT_INTF_ID;
}

daqErrCode daqFloat_getValue(daqFloatObject* self, daqFloat* value)
{
    return reinterpret_cast<daq::IFloat*>(self)->getValue(value);
}

daqErrCode daqFloat_equalsValue(daqFloatObject* self, daqFloat value, daqBool* equals)
{
    return reinterpret_cast<daq::IFloat*>(self)->equalsValue(value, equals);
}

daqErrCode daqFloat_createFloat(daqFloatObject** obj, daqFloat value)
{
    daq::IFloat* ptr = nullptr;
    daqErrCode err = daq::createFloat(&ptr, value);
    *obj = reinterpret_cast<daqFloatObject*>(ptr);
    return err;
}

daqErrCode daqFloat_createFloatObject(daqFloatObject** obj, daqFloat value)
{
    daq::IFloat* ptr = nullptr;
    daqErrCode err = daq::createFloatObject(&ptr, value);
    *obj = reinterpret_cast<daqFloatObject*>(ptr);
    return err;
}
