//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/function.h>

#include <opendaq/opendaq.h>
#include <coretypes/function.h>

#include <copendaq_private.h>

const daqIntfID DAQ_FUNCTION_INTF_ID = { daq::IFunction::Id.Data1, daq::IFunction::Id.Data2, daq::IFunction::Id.Data3, daq::IFunction::Id.Data4_UInt64 };

void daqFunction_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_FUNCTION_INTF_ID;
}

daqErrCode daqFunction_call(daqFunctionObject* self, daqBaseObject* params, daqBaseObject** result)
{
    return reinterpret_cast<daq::IFunction*>(self)->call(reinterpret_cast<daq::IBaseObject*>(params), reinterpret_cast<daq::IBaseObject**>(result));
}

daqErrCode daqFunction_createFunction(daqFunctionObject** obj, daqFuncCall value)
{
    daq::IFunction* ptr = nullptr;
    daqErrCode err = daq::createFunction(&ptr, reinterpret_cast<daq::FuncCall>(value));
    *obj = reinterpret_cast<daqFunctionObject*>(ptr);
    return err;
}
