//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/inspectable.h>

#include <opendaq/opendaq.h>
#include <coretypes/inspectable.h>

#include <copendaq_private.h>

const daqIntfID DAQ_INSPECTABLE_INTF_ID = { daq::IInspectable::Id.Data1, daq::IInspectable::Id.Data2, daq::IInspectable::Id.Data3, daq::IInspectable::Id.Data4_UInt64 };

void daqInspectable_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_INSPECTABLE_INTF_ID;
}

/*
daqErrCode daqInspectable_getInterfaceIds(daqInspectable* self, daqSizeT* idCount, daqIntfID** ids)
{
    return reinterpret_cast<daq::IInspectable*>(self)->getInterfaceIds(idCount, copendaq::utils::toDaqIntfId(ids));
}
*/

daqErrCode daqInspectable_getRuntimeClassName(daqInspectable* self, daqStringObject** implementationName)
{
    return reinterpret_cast<daq::IInspectable*>(self)->getRuntimeClassName(reinterpret_cast<daq::IString**>(implementationName));
}
