//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/procedure.h>

#include <opendaq/opendaq.h>
#include <coretypes/procedure.h>

#include <copendaq_private.h>

const daqIntfID DAQ_PROCEDURE_INTF_ID = { daq::IProcedure::Id.Data1, daq::IProcedure::Id.Data2, daq::IProcedure::Id.Data3, daq::IProcedure::Id.Data4_UInt64 };

void daqProcedure_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_PROCEDURE_INTF_ID;
}

daqErrCode daqProcedure_dispatch(daqProcedure* self, daqBaseObject* params)
{
    return reinterpret_cast<daq::IProcedure*>(self)->dispatch(reinterpret_cast<daq::IBaseObject*>(params));
}

daqErrCode daqProcedure_createProcedure(daqProcedure** obj, daqProcCall value)
{
    daq::IProcedure* ptr = nullptr;
    daqErrCode err = daq::createProcedure(&ptr, reinterpret_cast<daq::ProcCall>(value));
    *obj = reinterpret_cast<daqProcedure*>(ptr);
    return err;
}
