//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/serialized_object.h>

#include <opendaq/opendaq.h>
#include <coretypes/serialized_object.h>

#include <copendaq_private.h>

const daqIntfID DAQ_SERIALIZED_OBJECT_INTF_ID = { daq::ISerializedObject::Id.Data1, daq::ISerializedObject::Id.Data2, daq::ISerializedObject::Id.Data3, daq::ISerializedObject::Id.Data4_UInt64 };

void daqSerializedObject_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_SERIALIZED_OBJECT_INTF_ID;
}

daqErrCode daqSerializedObject_readSerializedObject(daqSerializedObject* self, daqStringObject* key, daqSerializedObject** plainObj)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readSerializedObject(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::ISerializedObject**>(plainObj));
}

daqErrCode daqSerializedObject_readSerializedList(daqSerializedObject* self, daqStringObject* key, daqSerializedList** list)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readSerializedList(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::ISerializedList**>(list));
}

daqErrCode daqSerializedObject_readList(daqSerializedObject* self, daqStringObject* key, daqBaseObject* context, daqFunctionObject* factoryCallback, daqListObject** list)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readList(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::IBaseObject*>(context), reinterpret_cast<daq::IFunction*>(factoryCallback), reinterpret_cast<daq::IList**>(list));
}

daqErrCode daqSerializedObject_readObject(daqSerializedObject* self, daqStringObject* key, daqBaseObject* context, daqFunctionObject* factoryCallback, daqBaseObject** obj)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readObject(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::IBaseObject*>(context), reinterpret_cast<daq::IFunction*>(factoryCallback), reinterpret_cast<daq::IBaseObject**>(obj));
}

daqErrCode daqSerializedObject_readString(daqSerializedObject* self, daqStringObject* key, daqStringObject** string)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readString(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::IString**>(string));
}

daqErrCode daqSerializedObject_readBool(daqSerializedObject* self, daqStringObject* key, daqBool* boolean)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readBool(reinterpret_cast<daq::IString*>(key), boolean);
}

daqErrCode daqSerializedObject_readFloat(daqSerializedObject* self, daqStringObject* key, daqFloat* real)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readFloat(reinterpret_cast<daq::IString*>(key), real);
}

daqErrCode daqSerializedObject_readInt(daqSerializedObject* self, daqStringObject* key, daqInt* integer)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->readInt(reinterpret_cast<daq::IString*>(key), integer);
}

daqErrCode daqSerializedObject_hasKey(daqSerializedObject* self, daqStringObject* key, daqBool* hasKey)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->hasKey(reinterpret_cast<daq::IString*>(key), hasKey);
}

daqErrCode daqSerializedObject_getKeys(daqSerializedObject* self, daqListObject** list)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->getKeys(reinterpret_cast<daq::IList**>(list));
}

daqErrCode daqSerializedObject_getType(daqSerializedObject* self, daqStringObject* key, daqCoreType* type)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->getType(reinterpret_cast<daq::IString*>(key), reinterpret_cast<daq::CoreType*>(type));
}

daqErrCode daqSerializedObject_isRoot(daqSerializedObject* self, daqBool* isRoot)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->isRoot(isRoot);
}

daqErrCode daqSerializedObject_toJson(daqSerializedObject* self, daqStringObject** jsonString)
{
    return reinterpret_cast<daq::ISerializedObject*>(self)->toJson(reinterpret_cast<daq::IString**>(jsonString));
}
