//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/stringobject.h>

#include <opendaq/opendaq.h>
#include <coretypes/stringobject.h>

#include <copendaq_private.h>

const daqIntfID DAQ_STRING_INTF_ID = { daq::IString::Id.Data1, daq::IString::Id.Data2, daq::IString::Id.Data3, daq::IString::Id.Data4_UInt64 };

void daqString_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_STRING_INTF_ID;
}

daqErrCode daqString_getCharPtr(daqString* self, daqCConstCharPtr* value)
{
    return reinterpret_cast<daq::IString*>(self)->getCharPtr(reinterpret_cast<daq::ConstCharPtr*>(value));
}

daqErrCode daqString_getLength(daqString* self, daqCSizeT* size)
{
    return reinterpret_cast<daq::IString*>(self)->getLength(size);
}

daqErrCode daqString_createString(daqString** obj, daqCConstCharPtr str)
{
    daq::IString* ptr = nullptr;
    daqErrCode err = daq::createString(&ptr, static_cast<daq::ConstCharPtr>(str));
    *obj = reinterpret_cast<daqString*>(ptr);
    return err;
}

daqErrCode daqString_createStringN(daqString** obj, daqCConstCharPtr str, daqCSizeT length)
{
    daq::IString* ptr = nullptr;
    daqErrCode err = daq::createStringN(&ptr, static_cast<daq::ConstCharPtr>(str), length);
    *obj = reinterpret_cast<daqString*>(ptr);
    return err;
}
