//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/struct_builder.h>

#include <opendaq/opendaq.h>
#include <coretypes/struct_builder.h>

#include <copendaq_private.h>

const daqIntfID DAQ_STRUCT_BUILDER_INTF_ID = { daq::IStructBuilder::Id.Data1, daq::IStructBuilder::Id.Data2, daq::IStructBuilder::Id.Data3, daq::IStructBuilder::Id.Data4_UInt64 };

void daqStructBuilder_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_STRUCT_BUILDER_INTF_ID;
}

daqErrCode daqStructBuilder_build(daqStructBuilder* self, daqStructObject** struct_)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->build(reinterpret_cast<daq::IStruct**>(struct_));
}

daqErrCode daqStructBuilder_getStructType(daqStructBuilder* self, daqStructType** type)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->getStructType(reinterpret_cast<daq::IStructType**>(type));
}

daqErrCode daqStructBuilder_getFieldNames(daqStructBuilder* self, daqListObject** names)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->getFieldNames(reinterpret_cast<daq::IList**>(names));
}

daqErrCode daqStructBuilder_setFieldValues(daqStructBuilder* self, daqListObject* values)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->setFieldValues(reinterpret_cast<daq::IList*>(values));
}

daqErrCode daqStructBuilder_getFieldValues(daqStructBuilder* self, daqListObject** values)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->getFieldValues(reinterpret_cast<daq::IList**>(values));
}

daqErrCode daqStructBuilder_set(daqStructBuilder* self, daqStringObject* name, daqBaseObject* field)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->set(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IBaseObject*>(field));
}

daqErrCode daqStructBuilder_get(daqStructBuilder* self, daqStringObject* name, daqBaseObject** field)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->get(reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::IBaseObject**>(field));
}

daqErrCode daqStructBuilder_hasField(daqStructBuilder* self, daqStringObject* name, daqBool* contains)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->hasField(reinterpret_cast<daq::IString*>(name), contains);
}

daqErrCode daqStructBuilder_getAsDictionary(daqStructBuilder* self, daqDictObject** dictionary)
{
    return reinterpret_cast<daq::IStructBuilder*>(self)->getAsDictionary(reinterpret_cast<daq::IDict**>(dictionary));
}

daqErrCode daqStructBuilder_createStructBuilder(daqStructBuilder** obj, daqStringObject* name, daqTypeManager* typeManager)
{
    daq::IStructBuilder* ptr = nullptr;
    daqErrCode err = daq::createStructBuilder(&ptr, reinterpret_cast<daq::IString*>(name), reinterpret_cast<daq::ITypeManager*>(typeManager));
    *obj = reinterpret_cast<daqStructBuilder*>(ptr);
    return err;
}

daqErrCode daqStructBuilder_createStructBuilderFromStruct(daqStructBuilder** obj, daqStructObject* struct_)
{
    daq::IStructBuilder* ptr = nullptr;
    daqErrCode err = daq::createStructBuilderFromStruct(&ptr, reinterpret_cast<daq::IStruct*>(struct_));
    *obj = reinterpret_cast<daqStructBuilder*>(ptr);
    return err;
}
