//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <ccoretypes/weakref.h>

#include <opendaq/opendaq.h>
#include <coretypes/weakref.h>

#include <copendaq_private.h>

const daqIntfID DAQ_SUPPORTS_WEAK_REF_INTF_ID = { daq::ISupportsWeakRef::Id.Data1, daq::ISupportsWeakRef::Id.Data2, daq::ISupportsWeakRef::Id.Data3, daq::ISupportsWeakRef::Id.Data4_UInt64 };

void daqSupportsWeakRef_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_SUPPORTS_WEAK_REF_INTF_ID;
}

daqErrCode daqSupportsWeakRef_getWeakRef(daqSupportsWeakRef* self, daqWeakRef** weakRef)
{
    return reinterpret_cast<daq::ISupportsWeakRef*>(self)->getWeakRef(reinterpret_cast<daq::IWeakRef**>(weakRef));
}
