//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqModuleManagerUtils daqModuleManagerUtils;
    typedef struct daqListObject daqListObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqDevice daqDevice;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqComponent daqComponent;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqFunctionBlock daqFunctionBlock;
    typedef struct daqStreaming daqStreaming;
    typedef struct daqServer daqServer;
    typedef struct daqDeviceInfo daqDeviceInfo;

    EXPORTED extern const daqIntfID DAQ_MODULE_MANAGER_UTILS_INTF_ID;
    void EXPORTED daqModuleManagerUtils_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqModuleManagerUtils_getAvailableDevices(daqModuleManagerUtils* self, daqListObject** availableDevices);
    daqErrCode EXPORTED daqModuleManagerUtils_getAvailableDeviceTypes(daqModuleManagerUtils* self, daqDictObject** deviceTypes);
    daqErrCode EXPORTED daqModuleManagerUtils_createDevice(daqModuleManagerUtils* self, daqDevice** device, daqStringObject* connectionString, daqComponent* parent, daqPropertyObject* config);
    daqErrCode EXPORTED daqModuleManagerUtils_getAvailableFunctionBlockTypes(daqModuleManagerUtils* self, daqDictObject** functionBlockTypes);
    daqErrCode EXPORTED daqModuleManagerUtils_createFunctionBlock(daqModuleManagerUtils* self, daqFunctionBlock** functionBlock, daqStringObject* id, daqComponent* parent, daqPropertyObject* config, daqStringObject* localId);
    daqErrCode EXPORTED daqModuleManagerUtils_createStreaming(daqModuleManagerUtils* self, daqStreaming** streaming, daqStringObject* connectionString, daqPropertyObject* config);
    daqErrCode EXPORTED daqModuleManagerUtils_getAvailableStreamingTypes(daqModuleManagerUtils* self, daqDictObject** streamingTypes);
    daqErrCode EXPORTED daqModuleManagerUtils_createDefaultAddDeviceConfig(daqModuleManagerUtils* self, daqPropertyObject** defaultConfig);
    daqErrCode EXPORTED daqModuleManagerUtils_createServer(daqModuleManagerUtils* self, daqServer** server, daqStringObject* serverTypeId, daqDevice* rootDevice, daqPropertyObject* serverConfig);
    daqErrCode EXPORTED daqModuleManagerUtils_changeIpConfig(daqModuleManagerUtils* self, daqStringObject* iface, daqStringObject* manufacturer, daqStringObject* serialNumber, daqPropertyObject* config);
    daqErrCode EXPORTED daqModuleManagerUtils_requestIpConfig(daqModuleManagerUtils* self, daqStringObject* iface, daqStringObject* manufacturer, daqStringObject* serialNumber, daqPropertyObject** config);
    daqErrCode EXPORTED daqModuleManagerUtils_completeDeviceCapabilities(daqModuleManagerUtils* self, daqDevice* device);
    daqErrCode EXPORTED daqModuleManagerUtils_createDevices(daqModuleManagerUtils* self, daqDictObject** devices, daqDictObject* connectionArgs, daqComponent* parent, daqDictObject* errCodes, daqDictObject* errorInfos);
    daqErrCode EXPORTED daqModuleManagerUtils_getDiscoveryInfo(daqModuleManagerUtils* self, daqDeviceInfo** deviceInfo, daqStringObject* manufacturer, daqStringObject* serialNumber);

#ifdef __cplusplus
}
#endif
