//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/scheduler/work_repetitive.h>

#include <opendaq/opendaq.h>
#include <opendaq/work_repetitive.h>

#include <copendaq_private.h>

const daqIntfID DAQ_WORK_REPETITIVE_INTF_ID = { daq::IWorkRepetitive::Id.Data1, daq::IWorkRepetitive::Id.Data2, daq::IWorkRepetitive::Id.Data3, daq::IWorkRepetitive::Id.Data4_UInt64 };

void daqWorkRepetitive_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_WORK_REPETITIVE_INTF_ID;
}

daqErrCode daqWorkRepetitive_executeRepetitively(daqWorkRepetitive* self, daqBool* repeatAfter)
{
    return reinterpret_cast<daq::IWorkRepetitive*>(self)->executeRepetitively(repeatAfter);
}
