//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2026 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqMutex daqMutex;

    EXPORTED extern const daqIntfID DAQ_MUTEX_INTF_ID;
    void EXPORTED daqMutex_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqMutex_lock(daqMutex* self);
    daqErrCode EXPORTED daqMutex_tryLock(daqMutex* self, daqCBool* succeeded);
    daqErrCode EXPORTED daqMutex_unlock(daqMutex* self);
    daqErrCode EXPORTED daqMutex_createMutex(daqMutex** obj);

#ifdef __cplusplus
}
#endif
