//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqPropertyObjectInternal daqPropertyObjectInternal;
    typedef struct daqProperty daqProperty;
    typedef struct daqProcedureObject daqProcedureObject;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqLockGuard daqLockGuard;
    typedef struct daqMutex daqMutex;

    EXPORTED extern const daqIntfID DAQ_PROPERTY_OBJECT_INTERNAL_INTF_ID;
    void EXPORTED daqPropertyObjectInternal_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqPropertyObjectInternal_checkForReferences(daqPropertyObjectInternal* self, daqProperty* property, daqBool* isReferenced);
    daqErrCode EXPORTED daqPropertyObjectInternal_checkForReferencesNoLock(daqPropertyObjectInternal* self, daqProperty* property, daqBool* isReferenced);
    daqErrCode EXPORTED daqPropertyObjectInternal_enableCoreEventTrigger(daqPropertyObjectInternal* self);
    daqErrCode EXPORTED daqPropertyObjectInternal_disableCoreEventTrigger(daqPropertyObjectInternal* self);
    daqErrCode EXPORTED daqPropertyObjectInternal_getCoreEventTrigger(daqPropertyObjectInternal* self, daqProcedureObject** trigger);
    daqErrCode EXPORTED daqPropertyObjectInternal_setCoreEventTrigger(daqPropertyObjectInternal* self, daqProcedureObject* trigger);
    daqErrCode EXPORTED daqPropertyObjectInternal_clone(daqPropertyObjectInternal* self, daqPropertyObject** cloned);
    daqErrCode EXPORTED daqPropertyObjectInternal_setPath(daqPropertyObjectInternal* self, daqStringObject* path);
    daqErrCode EXPORTED daqPropertyObjectInternal_getPath(daqPropertyObjectInternal* self, daqStringObject** path);
    daqErrCode EXPORTED daqPropertyObjectInternal_isUpdating(daqPropertyObjectInternal* self, daqBool* updating);
    daqErrCode EXPORTED daqPropertyObjectInternal_hasUserReadAccess(daqPropertyObjectInternal* self, daqBaseObject* userContext, daqBool* hasAccessOut);
    daqErrCode EXPORTED daqPropertyObjectInternal_getPropertyValueNoLock(daqPropertyObjectInternal* self, daqStringObject* name, daqBaseObject** value);
    daqErrCode EXPORTED daqPropertyObjectInternal_getPropertySelectionValueNoLock(daqPropertyObjectInternal* self, daqStringObject* name, daqBaseObject** value);
    daqErrCode EXPORTED daqPropertyObjectInternal_setPropertyValueNoLock(daqPropertyObjectInternal* self, daqStringObject* name, daqBaseObject* value);
    daqErrCode EXPORTED daqPropertyObjectInternal_setProtectedPropertyValueNoLock(daqPropertyObjectInternal* self, daqStringObject* name, daqBaseObject* value);
    daqErrCode EXPORTED daqPropertyObjectInternal_clearPropertyValueNoLock(daqPropertyObjectInternal* self, daqStringObject* name);
    daqErrCode EXPORTED daqPropertyObjectInternal_getLockGuard(daqPropertyObjectInternal* self, daqLockGuard** lockGuard);
    daqErrCode EXPORTED daqPropertyObjectInternal_getRecursiveLockGuard(daqPropertyObjectInternal* self, daqLockGuard** lockGuard);
    daqErrCode EXPORTED daqPropertyObjectInternal_setLockingStrategy(daqPropertyObjectInternal* self, daqLockingStrategy strategy);
    daqErrCode EXPORTED daqPropertyObjectInternal_getLockingStrategy(daqPropertyObjectInternal* self, daqLockingStrategy* strategy);
    daqErrCode EXPORTED daqPropertyObjectInternal_getMutex(daqPropertyObjectInternal* self, daqMutex** mutex);
    daqErrCode EXPORTED daqPropertyObjectInternal_getMutexOwner(daqPropertyObjectInternal* self, daqPropertyObjectInternal** owner);

#ifdef __cplusplus
}
#endif
