//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqProperty daqProperty;
    typedef struct daqEvent daqEvent;
    typedef struct daqListObject daqListObject;
    typedef struct daqPermissionManager daqPermissionManager;
    typedef struct daqSearchFilter daqSearchFilter;
    typedef struct daqTypeManager daqTypeManager;

    EXPORTED extern const daqIntfID DAQ_PROPERTY_OBJECT_INTF_ID;
    void EXPORTED daqPropertyObject_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqPropertyObject_getClassName(daqPropertyObject* self, daqStringObject** className);
    daqErrCode EXPORTED daqPropertyObject_setPropertyValue(daqPropertyObject* self, daqStringObject* propertyName, daqBaseObject* value);
    daqErrCode EXPORTED daqPropertyObject_getPropertyValue(daqPropertyObject* self, daqStringObject* propertyName, daqBaseObject** value);
    daqErrCode EXPORTED daqPropertyObject_getPropertySelectionValue(daqPropertyObject* self, daqStringObject* propertyName, daqBaseObject** value);
    daqErrCode EXPORTED daqPropertyObject_clearPropertyValue(daqPropertyObject* self, daqStringObject* propertyName);
    daqErrCode EXPORTED daqPropertyObject_hasProperty(daqPropertyObject* self, daqStringObject* propertyName, daqBool* hasProperty);
    daqErrCode EXPORTED daqPropertyObject_getProperty(daqPropertyObject* self, daqStringObject* propertyName, daqProperty** property);
    daqErrCode EXPORTED daqPropertyObject_addProperty(daqPropertyObject* self, daqProperty* property);
    daqErrCode EXPORTED daqPropertyObject_removeProperty(daqPropertyObject* self, daqStringObject* propertyName);
    daqErrCode EXPORTED daqPropertyObject_getOnPropertyValueWrite(daqPropertyObject* self, daqStringObject* propertyName, daqEvent** event);
    daqErrCode EXPORTED daqPropertyObject_getOnPropertyValueRead(daqPropertyObject* self, daqStringObject* propertyName, daqEvent** event);
    daqErrCode EXPORTED daqPropertyObject_getOnAnyPropertyValueWrite(daqPropertyObject* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyObject_getOnAnyPropertyValueRead(daqPropertyObject* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyObject_getVisibleProperties(daqPropertyObject* self, daqListObject** properties);
    daqErrCode EXPORTED daqPropertyObject_getAllProperties(daqPropertyObject* self, daqListObject** properties);
    daqErrCode EXPORTED daqPropertyObject_setPropertyOrder(daqPropertyObject* self, daqListObject* orderedPropertyNames);
    daqErrCode EXPORTED daqPropertyObject_beginUpdate(daqPropertyObject* self);
    daqErrCode EXPORTED daqPropertyObject_endUpdate(daqPropertyObject* self);
    daqErrCode EXPORTED daqPropertyObject_getUpdating(daqPropertyObject* self, daqBool* updating);
    daqErrCode EXPORTED daqPropertyObject_getOnEndUpdate(daqPropertyObject* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyObject_getPermissionManager(daqPropertyObject* self, daqPermissionManager** permissionManager);
    daqErrCode EXPORTED daqPropertyObject_findProperties(daqPropertyObject* self, daqListObject** properties, daqSearchFilter* propertyFilter, daqSearchFilter* componentFilter);
    daqErrCode EXPORTED daqPropertyObject_setPropertySelectionValue(daqPropertyObject* self, daqStringObject* propertyName, daqBaseObject* value);
    daqErrCode EXPORTED daqPropertyObject_clearPropertyValues(daqPropertyObject* self);
    daqErrCode EXPORTED daqPropertyObject_createPropertyObject(daqPropertyObject** obj);
    daqErrCode EXPORTED daqPropertyObject_createPropertyObjectWithClassAndManager(daqPropertyObject** obj, daqTypeManager* manager, daqStringObject* className);

#ifdef __cplusplus
}
#endif
