//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqProperty daqProperty;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqUnit daqUnit;
    typedef struct daqNumber daqNumber;
    typedef struct daqListObject daqListObject;
    typedef struct daqValidator daqValidator;
    typedef struct daqCoercer daqCoercer;
    typedef struct daqCallableInfo daqCallableInfo;
    typedef struct daqStructType daqStructType;
    typedef struct daqEvent daqEvent;
    typedef struct daqBooleanObject daqBooleanObject;
    typedef struct daqIntegerObject daqIntegerObject;
    typedef struct daqFloatObject daqFloatObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqRatioObject daqRatioObject;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqEvalValue daqEvalValue;
    typedef struct daqStructObject daqStructObject;
    typedef struct daqEnumerationObject daqEnumerationObject;

    EXPORTED extern const daqIntfID DAQ_PROPERTY_INTF_ID;
    void EXPORTED daqProperty_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqProperty_getValueType(daqProperty* self, daqCoreType* type);
    daqErrCode EXPORTED daqProperty_getKeyType(daqProperty* self, daqCoreType* type);
    daqErrCode EXPORTED daqProperty_getItemType(daqProperty* self, daqCoreType* type);
    daqErrCode EXPORTED daqProperty_getName(daqProperty* self, daqStringObject** name);
    daqErrCode EXPORTED daqProperty_getDescription(daqProperty* self, daqStringObject** description);
    daqErrCode EXPORTED daqProperty_getUnit(daqProperty* self, daqUnit** unit);
    daqErrCode EXPORTED daqProperty_getMinValue(daqProperty* self, daqNumber** min);
    daqErrCode EXPORTED daqProperty_getMaxValue(daqProperty* self, daqNumber** max);
    daqErrCode EXPORTED daqProperty_getDefaultValue(daqProperty* self, daqBaseObject** value);
    daqErrCode EXPORTED daqProperty_getSuggestedValues(daqProperty* self, daqListObject** values);
    daqErrCode EXPORTED daqProperty_getVisible(daqProperty* self, daqBool* visible);
    daqErrCode EXPORTED daqProperty_getReadOnly(daqProperty* self, daqBool* readOnly);
    daqErrCode EXPORTED daqProperty_getSelectionValues(daqProperty* self, daqBaseObject** values);
    daqErrCode EXPORTED daqProperty_getReferencedProperty(daqProperty* self, daqProperty** property);
    daqErrCode EXPORTED daqProperty_getIsReferenced(daqProperty* self, daqBool* isReferenced);
    daqErrCode EXPORTED daqProperty_getValidator(daqProperty* self, daqValidator** validator);
    daqErrCode EXPORTED daqProperty_getCoercer(daqProperty* self, daqCoercer** coercer);
    daqErrCode EXPORTED daqProperty_getCallableInfo(daqProperty* self, daqCallableInfo** callable);
    daqErrCode EXPORTED daqProperty_getStructType(daqProperty* self, daqStructType** structType);
    daqErrCode EXPORTED daqProperty_getOnPropertyValueWrite(daqProperty* self, daqEvent** event);
    daqErrCode EXPORTED daqProperty_getOnPropertyValueRead(daqProperty* self, daqEvent** event);
    daqErrCode EXPORTED daqProperty_getValue(daqProperty* self, daqBaseObject** value);
    daqErrCode EXPORTED daqProperty_setValue(daqProperty* self, daqBaseObject* value);
    daqErrCode EXPORTED daqProperty_getOnSuggestedValuesRead(daqProperty* self, daqEvent** event);
    daqErrCode EXPORTED daqProperty_getOnSelectionValuesRead(daqProperty* self, daqEvent** event);
    daqErrCode EXPORTED daqProperty_getPropertyType(daqProperty* self, daqPropertyType* type);
    daqErrCode EXPORTED daqProperty_createBoolProperty(daqProperty** obj, daqStringObject* name, daqBooleanObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createIntProperty(daqProperty** obj, daqStringObject* name, daqIntegerObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createFloatProperty(daqProperty** obj, daqStringObject* name, daqFloatObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createStringProperty(daqProperty** obj, daqStringObject* name, daqStringObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createListProperty(daqProperty** obj, daqStringObject* name, daqListObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createDictProperty(daqProperty** obj, daqStringObject* name, daqDictObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createRatioProperty(daqProperty** obj, daqStringObject* name, daqRatioObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createObjectProperty(daqProperty** obj, daqStringObject* name, daqPropertyObject* defaultValue);
    daqErrCode EXPORTED daqProperty_createReferenceProperty(daqProperty** obj, daqStringObject* name, daqEvalValue* referencedPropertyEval);
    daqErrCode EXPORTED daqProperty_createFunctionProperty(daqProperty** obj, daqStringObject* name, daqCallableInfo* callableInfo, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createSelectionProperty(daqProperty** obj, daqStringObject* name, daqListObject* selectionValues, daqIntegerObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createSparseSelectionProperty(daqProperty** obj, daqStringObject* name, daqDictObject* selectionValues, daqIntegerObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createStructProperty(daqProperty** obj, daqStringObject* name, daqStructObject* defaultValue, daqBooleanObject* visible);
    daqErrCode EXPORTED daqProperty_createEnumerationProperty(daqProperty** obj, daqStringObject* name, daqEnumerationObject* defaultValue, daqBooleanObject* visible);

#ifdef __cplusplus
}
#endif
