//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqPropertyBuilder daqPropertyBuilder;
    typedef struct daqProperty daqProperty;
    typedef struct daqStringObject daqStringObject;
    typedef struct daqUnit daqUnit;
    typedef struct daqNumber daqNumber;
    typedef struct daqListObject daqListObject;
    typedef struct daqBooleanObject daqBooleanObject;
    typedef struct daqEvalValue daqEvalValue;
    typedef struct daqValidator daqValidator;
    typedef struct daqCoercer daqCoercer;
    typedef struct daqCallableInfo daqCallableInfo;
    typedef struct daqEvent daqEvent;
    typedef struct daqIntegerObject daqIntegerObject;
    typedef struct daqFloatObject daqFloatObject;
    typedef struct daqDictObject daqDictObject;
    typedef struct daqRatioObject daqRatioObject;
    typedef struct daqPropertyObject daqPropertyObject;
    typedef struct daqStructObject daqStructObject;
    typedef struct daqEnumerationObject daqEnumerationObject;

    EXPORTED extern const daqIntfID DAQ_PROPERTY_BUILDER_INTF_ID;
    void EXPORTED daqPropertyBuilder_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqPropertyBuilder_build(daqPropertyBuilder* self, daqProperty** property);
    daqErrCode EXPORTED daqPropertyBuilder_setValueType(daqPropertyBuilder* self, daqCoreType type);
    daqErrCode EXPORTED daqPropertyBuilder_getValueType(daqPropertyBuilder* self, daqCoreType* type);
    daqErrCode EXPORTED daqPropertyBuilder_setName(daqPropertyBuilder* self, daqStringObject* name);
    daqErrCode EXPORTED daqPropertyBuilder_getName(daqPropertyBuilder* self, daqStringObject** name);
    daqErrCode EXPORTED daqPropertyBuilder_setDescription(daqPropertyBuilder* self, daqStringObject* description);
    daqErrCode EXPORTED daqPropertyBuilder_getDescription(daqPropertyBuilder* self, daqStringObject** description);
    daqErrCode EXPORTED daqPropertyBuilder_setUnit(daqPropertyBuilder* self, daqUnit* unit);
    daqErrCode EXPORTED daqPropertyBuilder_getUnit(daqPropertyBuilder* self, daqUnit** unit);
    daqErrCode EXPORTED daqPropertyBuilder_setMinValue(daqPropertyBuilder* self, daqNumber* min);
    daqErrCode EXPORTED daqPropertyBuilder_getMinValue(daqPropertyBuilder* self, daqNumber** min);
    daqErrCode EXPORTED daqPropertyBuilder_setMaxValue(daqPropertyBuilder* self, daqNumber* max);
    daqErrCode EXPORTED daqPropertyBuilder_getMaxValue(daqPropertyBuilder* self, daqNumber** max);
    daqErrCode EXPORTED daqPropertyBuilder_setDefaultValue(daqPropertyBuilder* self, daqBaseObject* value);
    daqErrCode EXPORTED daqPropertyBuilder_getDefaultValue(daqPropertyBuilder* self, daqBaseObject** value);
    daqErrCode EXPORTED daqPropertyBuilder_setSuggestedValues(daqPropertyBuilder* self, daqListObject* values);
    daqErrCode EXPORTED daqPropertyBuilder_getSuggestedValues(daqPropertyBuilder* self, daqListObject** values);
    daqErrCode EXPORTED daqPropertyBuilder_setVisible(daqPropertyBuilder* self, daqBooleanObject* visible);
    daqErrCode EXPORTED daqPropertyBuilder_getVisible(daqPropertyBuilder* self, daqBooleanObject** visible);
    daqErrCode EXPORTED daqPropertyBuilder_setReadOnly(daqPropertyBuilder* self, daqBooleanObject* readOnly);
    daqErrCode EXPORTED daqPropertyBuilder_getReadOnly(daqPropertyBuilder* self, daqBooleanObject** readOnly);
    daqErrCode EXPORTED daqPropertyBuilder_setSelectionValues(daqPropertyBuilder* self, daqBaseObject* values);
    daqErrCode EXPORTED daqPropertyBuilder_getSelectionValues(daqPropertyBuilder* self, daqBaseObject** values);
    daqErrCode EXPORTED daqPropertyBuilder_setReferencedProperty(daqPropertyBuilder* self, daqEvalValue* propertyEval);
    daqErrCode EXPORTED daqPropertyBuilder_getReferencedProperty(daqPropertyBuilder* self, daqEvalValue** propertyEval);
    daqErrCode EXPORTED daqPropertyBuilder_setValidator(daqPropertyBuilder* self, daqValidator* validator);
    daqErrCode EXPORTED daqPropertyBuilder_getValidator(daqPropertyBuilder* self, daqValidator** validator);
    daqErrCode EXPORTED daqPropertyBuilder_setCoercer(daqPropertyBuilder* self, daqCoercer* coercer);
    daqErrCode EXPORTED daqPropertyBuilder_getCoercer(daqPropertyBuilder* self, daqCoercer** coercer);
    daqErrCode EXPORTED daqPropertyBuilder_setCallableInfo(daqPropertyBuilder* self, daqCallableInfo* callable);
    daqErrCode EXPORTED daqPropertyBuilder_getCallableInfo(daqPropertyBuilder* self, daqCallableInfo** callable);
    daqErrCode EXPORTED daqPropertyBuilder_setOnPropertyValueWrite(daqPropertyBuilder* self, daqEvent* event);
    daqErrCode EXPORTED daqPropertyBuilder_getOnPropertyValueWrite(daqPropertyBuilder* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyBuilder_setOnPropertyValueRead(daqPropertyBuilder* self, daqEvent* event);
    daqErrCode EXPORTED daqPropertyBuilder_getOnPropertyValueRead(daqPropertyBuilder* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyBuilder_setOnSuggestedValuesRead(daqPropertyBuilder* self, daqEvent* event);
    daqErrCode EXPORTED daqPropertyBuilder_getOnSuggestedValuesRead(daqPropertyBuilder* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyBuilder_setOnSelectionValuesRead(daqPropertyBuilder* self, daqEvent* event);
    daqErrCode EXPORTED daqPropertyBuilder_getOnSelectionValuesRead(daqPropertyBuilder* self, daqEvent** event);
    daqErrCode EXPORTED daqPropertyBuilder_setIsIntegerValueSelection(daqPropertyBuilder* self, daqBool isIntegerValueSelection);
    daqErrCode EXPORTED daqPropertyBuilder_getIsIntegerValueSelection(daqPropertyBuilder* self, daqBool* isIntegerValueSelection);
    daqErrCode EXPORTED daqPropertyBuilder_createPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name);
    daqErrCode EXPORTED daqPropertyBuilder_createBoolPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqBooleanObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createIntPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqIntegerObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createFloatPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqFloatObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createStringPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqStringObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createListPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqListObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createDictPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqDictObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createRatioPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqRatioObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createObjectPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqPropertyObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createReferencePropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqEvalValue* referencedPropertyEval);
    daqErrCode EXPORTED daqPropertyBuilder_createFunctionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqCallableInfo* callableInfo);
    daqErrCode EXPORTED daqPropertyBuilder_createSelectionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqListObject* selectionValues, daqIntegerObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createSparseSelectionPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqDictObject* selectionValues, daqIntegerObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createStructPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqStructObject* defaultValue);
    daqErrCode EXPORTED daqPropertyBuilder_createEnumerationPropertyBuilder(daqPropertyBuilder** obj, daqStringObject* name, daqEnumerationObject* defaultValue);

#ifdef __cplusplus
}
#endif
