//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

/*
 * Copyright 2022-2025 openDAQ d.o.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

#include <ccommon.h>

    typedef struct daqLoggerSink daqLoggerSink;
    typedef struct daqStringObject daqStringObject;

    EXPORTED extern const daqIntfID DAQ_LOGGER_SINK_INTF_ID;
    void EXPORTED daqLoggerSink_getInterfaceId(daqIntfID* intfId);

    daqErrCode EXPORTED daqLoggerSink_setLevel(daqLoggerSink* self, daqLogLevel level);
    daqErrCode EXPORTED daqLoggerSink_getLevel(daqLoggerSink* self, daqLogLevel* level);
    daqErrCode EXPORTED daqLoggerSink_shouldLog(daqLoggerSink* self, daqLogLevel level, daqBool* willLog);
    daqErrCode EXPORTED daqLoggerSink_setPattern(daqLoggerSink* self, daqStringObject* pattern);
    daqErrCode EXPORTED daqLoggerSink_flush(daqLoggerSink* self);
    daqErrCode EXPORTED daqLoggerSink_createStdErrLoggerSink(daqLoggerSink** obj);
    daqErrCode EXPORTED daqLoggerSink_createStdOutLoggerSink(daqLoggerSink** obj);
    daqErrCode EXPORTED daqLoggerSink_createRotatingFileLoggerSink(daqLoggerSink** obj, daqStringObject* fileName, daqSizeT maxFileByteSize, daqSizeT maxFiles);
    daqErrCode EXPORTED daqLoggerSink_createBasicFileLoggerSink(daqLoggerSink** obj, daqStringObject* fileName);
#ifdef _WIN32
    daqErrCode EXPORTED daqLoggerSink_createWinDebugLoggerSink(daqLoggerSink** obj);
#endif

#ifdef __cplusplus
}
#endif
