//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     RTGen (CGenerator v0.7.0).
// </auto-generated>
//------------------------------------------------------------------------------

#include <copendaq/streaming/mirrored_input_port_private.h>

#include <opendaq/opendaq.h>
#include <opendaq/mirrored_input_port_private.h>

#include <copendaq_private.h>

const daqIntfID DAQ_MIRRORED_INPUT_PORT_PRIVATE_INTF_ID = { daq::IMirroredInputPortPrivate::Id.Data1, daq::IMirroredInputPortPrivate::Id.Data2, daq::IMirroredInputPortPrivate::Id.Data3, daq::IMirroredInputPortPrivate::Id.Data4_UInt64 };

void daqMirroredInputPortPrivate_getInterfaceId(daqIntfID* intfId)
{
    *intfId = DAQ_MIRRORED_INPUT_PORT_PRIVATE_INTF_ID;
}

daqErrCode daqMirroredInputPortPrivate_addStreamingSource(daqMirroredInputPortPrivate* self, daqStreaming* streaming)
{
    return reinterpret_cast<daq::IMirroredInputPortPrivate*>(self)->addStreamingSource(reinterpret_cast<daq::IStreaming*>(streaming));
}

daqErrCode daqMirroredInputPortPrivate_removeStreamingSource(daqMirroredInputPortPrivate* self, daqString* streamingConnectionString)
{
    return reinterpret_cast<daq::IMirroredInputPortPrivate*>(self)->removeStreamingSource(reinterpret_cast<daq::IString*>(streamingConnectionString));
}

daqErrCode daqMirroredInputPortPrivate_getActiveStreamingSourceObject(daqMirroredInputPortPrivate* self, daqStreaming** streaming)
{
    return reinterpret_cast<daq::IMirroredInputPortPrivate*>(self)->getActiveStreamingSourceObject(reinterpret_cast<daq::IStreaming**>(streaming));
}

daqErrCode daqMirroredInputPortPrivate_getStreamingSourceObjects(daqMirroredInputPortPrivate* self, daqList** objects)
{
    return reinterpret_cast<daq::IMirroredInputPortPrivate*>(self)->getStreamingSourceObjects(reinterpret_cast<daq::IList**>(objects));
}
